/**
 * @(#)JAIFrame 2026/03/20
 *
 * ICE Team free software group
 *
 * This file is part of C64 Java Software Emulator.
 * See README for copyright notice.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 *  02111-1307  USA.
 */
package sw_emulator.swing;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Frame;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import sw_emulator.software.ai.AIBackendConfig;
import sw_emulator.software.ai.M6510LabelAnalyzer;
import sw_emulator.software.ai.TokenUsage;
import sw_emulator.swing.table.LabelTableModel;

/**
 * Non-modal JFrame that shows the progress and results of an AI label
 * analysis request.
 *
 * Layout (fixed part, suitable for NetBeans GUI designer):
 *
 *   ┌──────────────────────────────────────────────────┐
 *   │  AI Label Analyzer                               │
 *   ├──────────────────────────────────────────────────┤
 *   │  Backend: LOCAL   Model: local-model             │
 *   │  Est. tokens: 312   Actual tokens: —             │
 *   │  Elapsed: 00:00                                  │
 *   ├──────────────────────────────────────────────────┤
 *   │  [  result container panel – swapped at runtime ]│  ← resultContainerPanel
 *   ├──────────────────────────────────────────────────┤
 *   │  [Select all] [Deselect all]   [Apply] [Cancel]  │
 *   └──────────────────────────────────────────────────┘
 *
 * Usage:
 *   AILabelFrame frame = new AILabelFrame(ownerFrame, analyzer);
 *   frame.setVisible(true);
 *   frame.startAnalysis(sourceText, currentLabels, labelConsumer);
 *
 * @author ice
 */
public class JAIFrame extends javax.swing.JFrame {
  
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JAIFrame.class.getName());
  
  private final M6510LabelAnalyzer analyzer;
  private Timer elapsedTimer;
  private long startTimeMs;
  
  /** 
   * Called when the user clicks Apply with the selected rows. 
   */
  public interface ApplyCallback {
    void onApply(List<LabelTableModel.Row> selectedRows);
  }

  private ApplyCallback applyCallback;
  private LabelResultPanel resultPanel;


  /**
   * Creates new form JAIFrame
   * 
   * @param owner the owner frame
   * @param analyzer the analyzer to use
   */
  public JAIFrame(Frame owner, M6510LabelAnalyzer analyzer) {
    super("AI Label Analyzer");
    this.analyzer = analyzer;
    initComponents();
    
    buildResultSlot();
    
    pack();
    // Position below the owner window
    if (owner != null) {
      int x = owner.getX();
      int y = owner.getY() + owner.getHeight() + 8;
      setLocation(x, y);
    }
    setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanelUp = new javax.swing.JPanel();
    jLabelBackend = new javax.swing.JLabel();
    jLabelEstimatedTokens = new javax.swing.JLabel();
    jLabelActualTokens = new javax.swing.JLabel();
    jLabelElapsedTime = new javax.swing.JLabel();
    jSeparatorVert = new javax.swing.JSeparator();
    jTextAreaStatus = new javax.swing.JTextArea();
    jPanelCn = new javax.swing.JPanel();
    jPanelDn = new javax.swing.JPanel();
    jButtonSelAll = new javax.swing.JButton();
    jButtonUnselAll = new javax.swing.JButton();
    jSeparatorVert2 = new javax.swing.JSeparator();
    jButtonApply = new javax.swing.JButton();
    jButtonCancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelUp.setBorder(javax.swing.BorderFactory.createTitledBorder("Request info"));
    jPanelUp.setLayout(new java.awt.GridBagLayout());

    jLabelBackend.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
    jLabelBackend.setText("Backend: - ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 6);
    jPanelUp.add(jLabelBackend, gridBagConstraints);

    jLabelEstimatedTokens.setText("Est. tokens: —");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 6);
    jPanelUp.add(jLabelEstimatedTokens, gridBagConstraints);

    jLabelActualTokens.setText("Actual tokens: —");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 6);
    jPanelUp.add(jLabelActualTokens, gridBagConstraints);

    jLabelElapsedTime.setForeground(new java.awt.Color(0, 100, 0));
    jLabelElapsedTime.setText("Elapsed: 00:00");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 6);
    jPanelUp.add(jLabelElapsedTime, gridBagConstraints);

    jSeparatorVert.setOrientation(javax.swing.SwingConstants.VERTICAL);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridheight = 2;
    jPanelUp.add(jSeparatorVert, gridBagConstraints);

    jTextAreaStatus.setEditable(false);
    jTextAreaStatus.setColumns(20);
    jTextAreaStatus.setForeground(new java.awt.Color(153, 153, 153));
    jTextAreaStatus.setLineWrap(true);
    jTextAreaStatus.setRows(2);
    jTextAreaStatus.setText("Ready");
    jTextAreaStatus.setWrapStyleWord(true);
    jTextAreaStatus.setBorder(null);
    jTextAreaStatus.setFocusable(false);
    jTextAreaStatus.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    jPanelUp.add(jTextAreaStatus, gridBagConstraints);

    getContentPane().add(jPanelUp, java.awt.BorderLayout.NORTH);

    jPanelCn.setBorder(javax.swing.BorderFactory.createTitledBorder("Suggested labels"));
    jPanelCn.setLayout(new java.awt.BorderLayout());
    getContentPane().add(jPanelCn, java.awt.BorderLayout.CENTER);

    jButtonSelAll.setText("Select all");
    jButtonSelAll.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSelAllActionPerformed(evt);
      }
    });
    jPanelDn.add(jButtonSelAll);

    jButtonUnselAll.setText("Deselect all");
    jButtonUnselAll.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonUnselAllActionPerformed(evt);
      }
    });
    jPanelDn.add(jButtonUnselAll);

    jSeparatorVert2.setOrientation(javax.swing.SwingConstants.VERTICAL);
    jPanelDn.add(jSeparatorVert2);

    jButtonApply.setText("Apply");
    jButtonApply.setEnabled(false);
    jButtonApply.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonApplyActionPerformed(evt);
      }
    });
    jPanelDn.add(jButtonApply);

    jButtonCancel.setText("Cancel");
    jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCancelActionPerformed(evt);
      }
    });
    jPanelDn.add(jButtonCancel);

    getContentPane().add(jPanelDn, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonSelAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelAllActionPerformed
    resultPanel.selectAll();
  }//GEN-LAST:event_jButtonSelAllActionPerformed

  private void jButtonUnselAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnselAllActionPerformed
    resultPanel.deselectAll();
  }//GEN-LAST:event_jButtonUnselAllActionPerformed

  private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
    onApply();
  }//GEN-LAST:event_jButtonApplyActionPerformed

  private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    onCancel();
  }//GEN-LAST:event_jButtonCancelActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new JAIFrame(null, null).setVisible(true));
  }
  
  /**
   * Center slot: replaced with a fresh LabelResultPanel at each run. 
   */
  private JPanel buildResultSlot() {
    resultPanel = new LabelResultPanel();
    jPanelCn.add(resultPanel, BorderLayout.CENTER);

    return resultPanel;
  }
  
   // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  /**
   * Starts an AI analysis in a background thread and updates the UI as it
   * progresses. Safe to call from the EDT.
   *
   * @param config        the configuration to use
   * @param source        disassembled source text to analyze
   * @param currentLabels labels currently present in the disassembler (addr->name)
   * @param knownLabels   labels found in previous calls (for context), may be null
   * @param callback      called on the EDT when the user clicks Apply
   */
  public void startAnalysis(AIBackendConfig config, CharSequence source,
                            Map<String, String> currentLabels,
                            Map<String, String> knownLabels,
                            ApplyCallback callback) {
    this.applyCallback = callback;

    // Reset UI
    resetUI();

    // Show estimated tokens immediately (no API call needed)
    int estimated = M6510LabelAnalyzer.estimateTokens(source);
    jLabelEstimatedTokens.setText("Est. tokens: " + estimated);

    // Backend info
    jLabelBackend.setText("Backend: " + config.getDisplayName()
            + "   Model: " + config.getModel());

    // Start elapsed timer
    startTimeMs = System.currentTimeMillis();
    elapsedTimer = new Timer(500, e -> updateElapsed());
    elapsedTimer.start();

    jTextAreaStatus.setText("Analyzing…");
    jButtonApply.setEnabled(false);

    // Launch background thread
    final String sourceSnap = source.toString();
    analyzer.analyzeLabelsAsync(config, 
            sourceSnap, knownLabels,
            suggestions -> SwingUtilities.invokeLater(() ->
                    onAnalysisComplete(suggestions, currentLabels)),
            error -> SwingUtilities.invokeLater(() ->
                    onAnalysisError(error)));
  }
  
  // ---------------------------------------------------------------------------
  // Private – analysis lifecycle
  // ---------------------------------------------------------------------------

  /**
   * Reset the UI interface
   */
  private void resetUI() {
    jLabelEstimatedTokens.setText("Est. tokens: —");
    jLabelActualTokens.setText("Actual tokens: —");
    jLabelElapsedTime.setText("Elapsed: 00:00");
    jTextAreaStatus.setText("Ready");
    jButtonApply.setEnabled(false);

    // Replace result panel with a fresh one
    jPanelCn.removeAll();
    resultPanel = new LabelResultPanel();
    jPanelCn.add(resultPanel, BorderLayout.CENTER);
    jPanelCn.revalidate();
    jPanelCn.repaint();

    if (elapsedTimer != null && elapsedTimer.isRunning()) elapsedTimer.stop();
  }
  
  
  /**
   * Update the elapsed time
   */
  private void updateElapsed() {
    long secs = (System.currentTimeMillis() - startTimeMs) / 1000;
    jLabelElapsedTime.setText(String.format("Elapsed: %02d:%02d", secs / 60, secs % 60));
  }
  
  
  /**
   * Code to execute when the analysis is complete
   * 
   * @param suggestions the suggested labels
   * @param currentLabels the current valid labels
   */
  private void onAnalysisComplete(Map<String, String> suggestions,
                                  Map<String, String> currentLabels) {
    // Stop timer
    if (elapsedTimer != null) elapsedTimer.stop();
    updateElapsed();  // final value

    // Show actual token usage
    TokenUsage usage = analyzer.getLastTokenUsage();
    jLabelActualTokens.setText("Actual tokens: " + usage.getTotalTokens()
            + "  (prompt " + usage.getPromptTokens()
            + " + completion " + usage.getCompletionTokens() + ")");

    // Populate table
    resultPanel.setResults(suggestions, currentLabels);

    // Update status
    int count = suggestions.size();
    jTextAreaStatus.setText(count + " label" + (count == 1 ? "" : "s") + " found");
    jTextAreaStatus.setForeground(count > 0 ? new Color(0, 120, 0) : Color.GRAY);
    jButtonApply.setEnabled(count > 0);

    // Bring window to front
    bringToFront();
  }
  
 /**
  * To be executed on alalysis error
  * 
  * @param ex the exception
  */ 
 private void onAnalysisError(Exception ex) {
    if (elapsedTimer != null) elapsedTimer.stop();
    updateElapsed();

    jTextAreaStatus.setText("Error: " + ex.getMessage());
    jTextAreaStatus.setForeground(Color.RED);
    jButtonApply.setEnabled(false);

    bringToFront();
  }

 /**
  * To be executed on apply button pressed
  */
  private void onApply() {
    List<LabelTableModel.Row> selected = resultPanel.getSelectedRows();
    if (applyCallback != null) applyCallback.onApply(selected);
    setVisible(false);
  }

  /**
   * To be executed on cancel button pressed
   */
  private void onCancel() {
    if (elapsedTimer != null) elapsedTimer.stop();
    setVisible(false);
  }  

  // ---------------------------------------------------------------------------
  // Private – bring to front (works around Windows focus restrictions)
  // ---------------------------------------------------------------------------

  /**
   * Bring frame in front of main when analysis is finished
   */
  private void bringToFront() {
    // Standard approach
    setAlwaysOnTop(true);
    toFront();
    requestFocus();
    setAlwaysOnTop(false);  // release so it doesn't stay above everything

    // Taskbar flash (Windows): requesting focus on a non-focused window
    // triggers the orange taskbar flash automatically on Windows
  } 
   
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonApply;
  private javax.swing.JButton jButtonCancel;
  private javax.swing.JButton jButtonSelAll;
  private javax.swing.JButton jButtonUnselAll;
  private javax.swing.JLabel jLabelActualTokens;
  private javax.swing.JLabel jLabelBackend;
  private javax.swing.JLabel jLabelElapsedTime;
  private javax.swing.JLabel jLabelEstimatedTokens;
  private javax.swing.JPanel jPanelCn;
  private javax.swing.JPanel jPanelDn;
  private javax.swing.JPanel jPanelUp;
  private javax.swing.JSeparator jSeparatorVert;
  private javax.swing.JSeparator jSeparatorVert2;
  private javax.swing.JTextArea jTextAreaStatus;
  // End of variables declaration//GEN-END:variables
}
