/**
 * @(#)JASPanel 2024/04/19
 *
 * ICE Team free software group
 *
 * This file is part of C64 Java Software Emulator.
 * See README for copyright notice.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 *  02111-1307  USA.
 */
package sw_emulator.swing;

import sw_emulator.software.Assembler;
import sw_emulator.swing.main.Option;

/**
 * A panel for AS assembler option 
 * 
 * @author ice
 */
public class JASPanel extends javax.swing.JPanel {
    /** Option file to use */
    Option option;
    
    /**
     * Creates new form JASPanel
     */
    public JASPanel() {
        initComponents();
    }
    
    /**
     * Set up the panel with the option 
     * 
     * @param option the option to use
     */
    public void setUp(Option option) {
      this.option=option;
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelASLabelDeclaration = new javax.swing.JLabel();
    jRadioButtonASLabelName = new javax.swing.JRadioButton();
    jScrollPaneASByte = new javax.swing.JScrollPane();
    jTextPaneGlassLabelName = new javax.swing.JTextPane();
    jLabelASByteDeclaration = new javax.swing.JLabel();
    jRadioButtonASDbByte = new javax.swing.JRadioButton();
    jScrollPaneASWord = new javax.swing.JScrollPane();
    jTextPaneASDbByte = new javax.swing.JTextPane();
    jLabelASWordDeclaration = new javax.swing.JLabel();
    jRadioButtonASDwWord = new javax.swing.JRadioButton();
    jScrollPaneASDotWord = new javax.swing.JScrollPane();
    jTextPaneASDwWord = new javax.swing.JTextPane();
    jLabelASCommentDeclaration = new javax.swing.JLabel();
    jRadioButtonASSemicolonComment = new javax.swing.JRadioButton();
    jScrollPaneASSemicolonComment = new javax.swing.JScrollPane();
    jTextPaneASSemicolonComment = new javax.swing.JTextPane();
    jLabelASBlockCommentDeclaration = new javax.swing.JLabel();
    jRadioButtonASSemicolonBlockComment = new javax.swing.JRadioButton();
    jScrollPaneASSemicolonBlockComment1 = new javax.swing.JScrollPane();
    jTextPaneTmpxSemicolonBlockComment1 = new javax.swing.JTextPane();
    jLabelASOriginDeclaration = new javax.swing.JLabel();
    jRadioButtonASOrigin = new javax.swing.JRadioButton();
    jScrollPaneASAsterixOrigin1 = new javax.swing.JScrollPane();
    jTextPaneASOrigin = new javax.swing.JTextPane();
    jLabelASStartingDeclaration = new javax.swing.JLabel();
    jRadioButtonASStarting = new javax.swing.JRadioButton();
    jScrollPaneASStarting = new javax.swing.JScrollPane();
    jTextPaneASStarting = new javax.swing.JTextPane();
    jLabelASMonoSpriteDeclaration = new javax.swing.JLabel();
    jLabelASMultiSpriteDeclaration = new javax.swing.JLabel();
    jRadioButtonASByteHexMonoSprite = new javax.swing.JRadioButton();
    jRadioButtonASByteHexMultiSprite = new javax.swing.JRadioButton();
    jScrollPaneASByteHexMultiSprite = new javax.swing.JScrollPane();
    TmpxPaneGlassByteHexMultiSprite = new javax.swing.JTextPane();
    jScrollPaneASByteHexMonoSprite = new javax.swing.JScrollPane();
    jTextPaneGlassByteHexMonoSprite = new javax.swing.JTextPane();
    jRadioButtonASByteBinMonoSprite = new javax.swing.JRadioButton();
    jRadioButtonASByteBinMultiSprite = new javax.swing.JRadioButton();
    jScrollPaneASByteBinMultiSprite = new javax.swing.JScrollPane();
    jTextPaneGlassByteBinMultiSprite = new javax.swing.JTextPane();
    jScrollPaneASByteBinMonoSprite = new javax.swing.JScrollPane();
    jTextPaneGlassByteBinMonoSprite = new javax.swing.JTextPane();
    jRadioButtonASMacroHexMonoSprite = new javax.swing.JRadioButton();
    jRadioButtonASMacroHexMultiSprite = new javax.swing.JRadioButton();
    jScrollPaneASMacroHexMultiSprite = new javax.swing.JScrollPane();
    jTextPaneGlassMacroHexMultiSprite = new javax.swing.JTextPane();
    jScrollPaneASMacroHexMonoSprite = new javax.swing.JScrollPane();
    jTextPaneGlassMacroHexMonoSprite = new javax.swing.JTextPane();
    jRadioButtonASMacroBinMonoSprite = new javax.swing.JRadioButton();
    jRadioButtonASMacroBinMultiSprite = new javax.swing.JRadioButton();
    jScrollPaneASMacroBinMultiSprite = new javax.swing.JScrollPane();
    jTextPaneGlassMacroBinMultiSprite = new javax.swing.JTextPane();
    jScrollPaneASMacroBinMonoSprite = new javax.swing.JScrollPane();
    jTextPaneGlassMacroBinMonoSprite = new javax.swing.JTextPane();
    jLabelASTribyteDeclaration = new javax.swing.JLabel();
    jRadioButtonASMacroTribyte = new javax.swing.JRadioButton();
    jScrollPaneASMacroTribyte = new javax.swing.JScrollPane();
    jTextPaneGlassMacroTribyte = new javax.swing.JTextPane();
    jLabelASLongDeclaration = new javax.swing.JLabel();
    jRadioButtonASDdLong = new javax.swing.JRadioButton();
    jScrollPaneASMacroLong = new javax.swing.JScrollPane();
    jTextPaneGlassMacroLong = new javax.swing.JTextPane();
    jLabelASWordSwappedDeclaration = new javax.swing.JLabel();
    jRadioButtonASMacroWordSwapped = new javax.swing.JRadioButton();
    jScrollPaneASMacroWordSwapped = new javax.swing.JScrollPane();
    jTextPaneGlassMacroWordSwapped = new javax.swing.JTextPane();
    jLabelASTextDeclaration = new javax.swing.JLabel();
    jRadioButtonASDbText = new javax.swing.JRadioButton();
    jScrollPaneASDotText = new javax.swing.JScrollPane();
    jTextPaneGlassDbText = new javax.swing.JTextPane();
    jLabelASNumTextDeclaration = new javax.swing.JLabel();
    jRadioButtonASDbNumText = new javax.swing.JRadioButton();
    jScrollPaneASDotTextNumText = new javax.swing.JScrollPane();
    jTextPaneGlassDbNumText = new javax.swing.JTextPane();
    jLabelASZeroTextDeclaration = new javax.swing.JLabel();
    jRadioButtonASDbZeroText = new javax.swing.JRadioButton();
    jScrollPaneASDotNullZeroText = new javax.swing.JScrollPane();
    jTextPaneGlassDbZeroText = new javax.swing.JTextPane();
    jLabelASAddressDeclaration = new javax.swing.JLabel();
    jRadioButtonASDwAddress = new javax.swing.JRadioButton();
    jScrollPaneASDotAddrAddress = new javax.swing.JScrollPane();
    jTextPaneGlassDwAddress = new javax.swing.JTextPane();
    jLabelTmpxASStackWordDeclaration = new javax.swing.JLabel();
    jRadioButtonASMacroStackWord = new javax.swing.JRadioButton();
    jScrollPaneASDotRtaStackWord = new javax.swing.JScrollPane();
    jTextPaneGlassMacroStackWord = new javax.swing.JTextPane();
    jLabelASHighTextDeclaration = new javax.swing.JLabel();
    jRadioButtonASDbHighText = new javax.swing.JRadioButton();
    jScrollPaneASDotShiftHighText = new javax.swing.JScrollPane();
    jTextPaneGlassDbHighText = new javax.swing.JTextPane();
    jLabelASShiftTextDeclaration = new javax.swing.JLabel();
    jRadioButtonASDbShiftText = new javax.swing.JRadioButton();
    jScrollPaneASDotShiftlShiftText = new javax.swing.JScrollPane();
    jTextPaneGlassDbShiftText = new javax.swing.JTextPane();
    jLabelASScreenTextDeclaration = new javax.swing.JLabel();
    jRadioButtonASDbScreenText = new javax.swing.JRadioButton();
    jScrollPaneASDotScreenText = new javax.swing.JScrollPane();
    jTextPaneDbScreenText = new javax.swing.JTextPane();
    jLabelASPetasciiTextDeclaration = new javax.swing.JLabel();
    jRadioButtonASDbPetasciiText = new javax.swing.JRadioButton();
    jScrollPaneASDotPetasciiText = new javax.swing.JScrollPane();
    jTextPaneGlassDbPetasciiText = new javax.swing.JTextPane();
    jRadioButtonASLabelNameColon = new javax.swing.JRadioButton();
    jScrollPaneASLabelNameColon = new javax.swing.JScrollPane();
    jTextPaneGlassLabelNameColon = new javax.swing.JTextPane();

    jLabelASLabelDeclaration.setText("Label:");

    jRadioButtonASLabelName.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASLabelNameItemStateChanged(evt);
      }
    });

    jScrollPaneASByte.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASByte.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassLabelName.setEditable(false);
    jTextPaneGlassLabelName.setContentType("text/html"); // NOI18N
    jTextPaneGlassLabelName.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <font color='black'>zzzz</font>\n    </p\n  </body>\n</html>\n");
    jScrollPaneASByte.setViewportView(jTextPaneGlassLabelName);

    jLabelASByteDeclaration.setText("Byte:");

    jRadioButtonASDbByte.setSelected(true);
    jRadioButtonASDbByte.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDbByteItemStateChanged(evt);
      }
    });

    jScrollPaneASWord.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASWord.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneASDbByte.setEditable(false);
    jTextPaneASDbByte.setContentType("text/html"); // NOI18N
    jTextPaneASDbByte.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>$xx</font> | <b> db</b> <font color='red'>xxh</font><br>\n     <b> db</b> <font color='blue'>dd</font> | <b> db</b> <font color='blue'>dd</font><br>\n     <b> db</b> <font color='green'>%nn</font> | <b> db</b> <font color='green'>nnb</font><br>\n     <b> db</b> <font color='purple'>'c'</font>  |  <b> db</b> <font color='purple'>'c'</font>\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASWord.setViewportView(jTextPaneASDbByte);

    jLabelASWordDeclaration.setText("Word:");

    jRadioButtonASDwWord.setSelected(true);
    jRadioButtonASDwWord.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDwWordItemStateChanged(evt);
      }
    });

    jScrollPaneASDotWord.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotWord.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneASDwWord.setEditable(false);
    jTextPaneASDwWord.setContentType("text/html"); // NOI18N
    jTextPaneASDwWord.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> dw</b> <font color='red'>$xxyy</font> | <b> dw</b> <font color='red'>xxyyh</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASDotWord.setViewportView(jTextPaneASDwWord);

    jLabelASCommentDeclaration.setText("Comment:");

    jRadioButtonASSemicolonComment.setSelected(true);
    jRadioButtonASSemicolonComment.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASSemicolonCommentItemStateChanged(evt);
      }
    });

    jScrollPaneASSemicolonComment.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASSemicolonComment.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneASSemicolonComment.setEditable(false);
    jTextPaneASSemicolonComment.setContentType("text/html"); // NOI18N
    jTextPaneASSemicolonComment.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <b>;</b> xxx\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASSemicolonComment.setViewportView(jTextPaneASSemicolonComment);

    jLabelASBlockCommentDeclaration.setText("Block Comment:");

    jRadioButtonASSemicolonBlockComment.setSelected(true);
    jRadioButtonASSemicolonBlockComment.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASSemicolonBlockCommentItemStateChanged(evt);
      }
    });

    jScrollPaneASSemicolonBlockComment1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASSemicolonBlockComment1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneTmpxSemicolonBlockComment1.setEditable(false);
    jTextPaneTmpxSemicolonBlockComment1.setContentType("text/html"); // NOI18N
    jTextPaneTmpxSemicolonBlockComment1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <b>;</b> xxx\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASSemicolonBlockComment1.setViewportView(jTextPaneTmpxSemicolonBlockComment1);

    jLabelASOriginDeclaration.setText("Origin:");

    jRadioButtonASOrigin.setSelected(true);
    jRadioButtonASOrigin.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASOriginItemStateChanged(evt);
      }
    });

    jScrollPaneASAsterixOrigin1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASAsterixOrigin1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneASOrigin.setEditable(false);
    jTextPaneASOrigin.setContentType("text/html"); // NOI18N
    jTextPaneASOrigin.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <b>org</b> $xxyy | <b>org</b> xxyyh\n    </p>\n  </body>\n</html>\n\n");
    jScrollPaneASAsterixOrigin1.setViewportView(jTextPaneASOrigin);

    jLabelASStartingDeclaration.setText("Starting:");

    jRadioButtonASStarting.setSelected(true);
    jRadioButtonASStarting.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASStartingItemStateChanged(evt);
      }
    });

    jScrollPaneASStarting.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASStarting.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneASStarting.setEditable(false);
    jTextPaneASStarting.setContentType("text/html"); // NOI18N
    jTextPaneASStarting.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <b>cpu</b> 6502 | <b> cpu</b> 8048\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASStarting.setViewportView(jTextPaneASStarting);

    jLabelASMonoSpriteDeclaration.setText("Monocolor sprite:");

    jLabelASMultiSpriteDeclaration.setText("Multicolor sprite:");

    jRadioButtonASByteHexMonoSprite.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASByteHexMonoSpriteItemStateChanged(evt);
      }
    });

    jRadioButtonASByteHexMultiSprite.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASByteHexMultiSpriteItemStateChanged(evt);
      }
    });

    jScrollPaneASByteHexMultiSprite.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASByteHexMultiSprite.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    TmpxPaneGlassByteHexMultiSprite.setEditable(false);
    TmpxPaneGlassByteHexMultiSprite.setContentType("text/html"); // NOI18N
    TmpxPaneGlassByteHexMultiSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> [byte]</b> <font color='red'>$xx..</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASByteHexMultiSprite.setViewportView(TmpxPaneGlassByteHexMultiSprite);

    jScrollPaneASByteHexMonoSprite.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASByteHexMonoSprite.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassByteHexMonoSprite.setEditable(false);
    jTextPaneGlassByteHexMonoSprite.setContentType("text/html"); // NOI18N
    jTextPaneGlassByteHexMonoSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> [byte]</b> <font color='red'>$xx..</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASByteHexMonoSprite.setViewportView(jTextPaneGlassByteHexMonoSprite);

    jRadioButtonASByteBinMonoSprite.setSelected(true);
    jRadioButtonASByteBinMonoSprite.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASByteBinMonoSpriteItemStateChanged(evt);
      }
    });

    jRadioButtonASByteBinMultiSprite.setSelected(true);
    jRadioButtonASByteBinMultiSprite.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASByteBinMultiSpriteItemStateChanged(evt);
      }
    });

    jScrollPaneASByteBinMultiSprite.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASByteBinMultiSprite.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassByteBinMultiSprite.setEditable(false);
    jTextPaneGlassByteBinMultiSprite.setContentType("text/html"); // NOI18N
    jTextPaneGlassByteBinMultiSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[byte]</b> <font color='red'>%b..</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASByteBinMultiSprite.setViewportView(jTextPaneGlassByteBinMultiSprite);

    jScrollPaneASByteBinMonoSprite.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASByteBinMonoSprite.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassByteBinMonoSprite.setEditable(false);
    jTextPaneGlassByteBinMonoSprite.setContentType("text/html"); // NOI18N
    jTextPaneGlassByteBinMonoSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[byte]</b> <font color='red'>%b..</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASByteBinMonoSprite.setViewportView(jTextPaneGlassByteBinMonoSprite);

    jRadioButtonASMacroHexMonoSprite.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASMacroHexMonoSpriteItemStateChanged(evt);
      }
    });

    jRadioButtonASMacroHexMultiSprite.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASMacroHexMultiSpriteItemStateChanged(evt);
      }
    });

    jScrollPaneASMacroHexMultiSprite.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASMacroHexMultiSprite.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassMacroHexMultiSprite.setEditable(false);
    jTextPaneGlassMacroHexMultiSprite.setContentType("text/html"); // NOI18N
    jTextPaneGlassMacroHexMultiSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac] </b> <font color='red'>$xx..</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASMacroHexMultiSprite.setViewportView(jTextPaneGlassMacroHexMultiSprite);

    jScrollPaneASMacroHexMonoSprite.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASMacroHexMonoSprite.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassMacroHexMonoSprite.setEditable(false);
    jTextPaneGlassMacroHexMonoSprite.setContentType("text/html"); // NOI18N
    jTextPaneGlassMacroHexMonoSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac] </b> <font color='red'>$xx..</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASMacroHexMonoSprite.setViewportView(jTextPaneGlassMacroHexMonoSprite);

    jRadioButtonASMacroBinMonoSprite.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASMacroBinMonoSpriteItemStateChanged(evt);
      }
    });

    jRadioButtonASMacroBinMultiSprite.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASMacroBinMultiSpriteItemStateChanged(evt);
      }
    });

    jScrollPaneASMacroBinMultiSprite.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASMacroBinMultiSprite.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassMacroBinMultiSprite.setEditable(false);
    jTextPaneGlassMacroBinMultiSprite.setContentType("text/html"); // NOI18N
    jTextPaneGlassMacroBinMultiSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac] </b> <font color='red'>%b..</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASMacroBinMultiSprite.setViewportView(jTextPaneGlassMacroBinMultiSprite);

    jScrollPaneASMacroBinMonoSprite.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASMacroBinMonoSprite.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassMacroBinMonoSprite.setEditable(false);
    jTextPaneGlassMacroBinMonoSprite.setContentType("text/html"); // NOI18N
    jTextPaneGlassMacroBinMonoSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac] </b> <font color='red'>%b..</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASMacroBinMonoSprite.setViewportView(jTextPaneGlassMacroBinMonoSprite);

    jLabelASTribyteDeclaration.setText("Tribyte:");

    jRadioButtonASMacroTribyte.setSelected(true);
    jRadioButtonASMacroTribyte.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASMacroTribyteItemStateChanged(evt);
      }
    });

    jScrollPaneASMacroTribyte.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASMacroTribyte.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassMacroTribyte.setEditable(false);
    jTextPaneGlassMacroTribyte.setContentType("text/html"); // NOI18N
    jTextPaneGlassMacroTribyte.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mc]</b> <font color='red'>$xxyyzz</font> |<b> [.mc]</b> <font color='red'>xxyyzzh</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASMacroTribyte.setViewportView(jTextPaneGlassMacroTribyte);

    jLabelASLongDeclaration.setText("Long:");

    jRadioButtonASDdLong.setSelected(true);
    jRadioButtonASDdLong.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDdLongItemStateChanged(evt);
      }
    });

    jScrollPaneASMacroLong.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASMacroLong.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassMacroLong.setEditable(false);
    jTextPaneGlassMacroLong.setContentType("text/html"); // NOI18N
    jTextPaneGlassMacroLong.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>dd</b> <font color='red'>$xx..kk</font> | <b>dd</b> <font color='red'>xx..kkh</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASMacroLong.setViewportView(jTextPaneGlassMacroLong);

    jLabelASWordSwappedDeclaration.setText("Word Swapped:");

    jRadioButtonASMacroWordSwapped.setSelected(true);
    jRadioButtonASMacroWordSwapped.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASMacroWordSwappedItemStateChanged(evt);
      }
    });

    jScrollPaneASMacroWordSwapped.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASMacroWordSwapped.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassMacroWordSwapped.setEditable(false);
    jTextPaneGlassMacroWordSwapped.setContentType("text/html"); // NOI18N
    jTextPaneGlassMacroWordSwapped.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac]</b> <font color='red'>$yyxx</font> | <b>[.mac]</b> <font color='red'>yyxxh</font><br>\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASMacroWordSwapped.setViewportView(jTextPaneGlassMacroWordSwapped);

    jLabelASTextDeclaration.setText("Text:");

    jRadioButtonASDbText.setSelected(true);
    jRadioButtonASDbText.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDbTextItemStateChanged(evt);
      }
    });

    jScrollPaneASDotText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassDbText.setEditable(false);
    jTextPaneGlassDbText.setContentType("text/html"); // NOI18N
    jTextPaneGlassDbText.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASDotText.setViewportView(jTextPaneGlassDbText);

    jLabelASNumTextDeclaration.setText("Text #num chars:");

    jRadioButtonASDbNumText.setSelected(true);
    jRadioButtonASDbNumText.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDbNumTextItemStateChanged(evt);
      }
    });

    jScrollPaneASDotTextNumText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotTextNumText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassDbNumText.setEditable(false);
    jTextPaneGlassDbNumText.setContentType("text/html"); // NOI18N
    jTextPaneGlassDbNumText.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jTextPaneGlassDbNumText.setPreferredSize(new java.awt.Dimension(66, 20));
    jScrollPaneASDotTextNumText.setViewportView(jTextPaneGlassDbNumText);

    jLabelASZeroTextDeclaration.setText("Text 0 terminated:");

    jRadioButtonASDbZeroText.setSelected(true);
    jRadioButtonASDbZeroText.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDbZeroTextItemStateChanged(evt);
      }
    });

    jScrollPaneASDotNullZeroText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotNullZeroText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassDbZeroText.setEditable(false);
    jTextPaneGlassDbZeroText.setContentType("text/html"); // NOI18N
    jTextPaneGlassDbZeroText.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASDotNullZeroText.setViewportView(jTextPaneGlassDbZeroText);

    jLabelASAddressDeclaration.setText("Address:");

    jRadioButtonASDwAddress.setSelected(true);
    jRadioButtonASDwAddress.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDwAddressItemStateChanged(evt);
      }
    });

    jScrollPaneASDotAddrAddress.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotAddrAddress.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassDwAddress.setEditable(false);
    jTextPaneGlassDwAddress.setContentType("text/html"); // NOI18N
    jTextPaneGlassDwAddress.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> dw</b> <font color='red'>$xxyy</font>| <b> dw</b> <font color='red'>xxyyh</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASDotAddrAddress.setViewportView(jTextPaneGlassDwAddress);

    jLabelTmpxASStackWordDeclaration.setText("Stack Word:");

    jRadioButtonASMacroStackWord.setSelected(true);
    jRadioButtonASMacroStackWord.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASMacroStackWordItemStateChanged(evt);
      }
    });

    jScrollPaneASDotRtaStackWord.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotRtaStackWord.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassMacroStackWord.setEditable(false);
    jTextPaneGlassMacroStackWord.setContentType("text/html"); // NOI18N
    jTextPaneGlassMacroStackWord.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac]</b> <font color='red'>$xxyy</font> | <b>[.mac]</b> <font color='red'>xxyyh</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASDotRtaStackWord.setViewportView(jTextPaneGlassMacroStackWord);

    jLabelASHighTextDeclaration.setText("Text '1' terminated:");

    jRadioButtonASDbHighText.setSelected(true);
    jRadioButtonASDbHighText.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDbHighTextItemStateChanged(evt);
      }
    });

    jScrollPaneASDotShiftHighText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotShiftHighText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassDbHighText.setEditable(false);
    jTextPaneGlassDbHighText.setContentType("text/html"); // NOI18N
    jTextPaneGlassDbHighText.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jTextPaneGlassDbHighText.setPreferredSize(new java.awt.Dimension(66, 20));
    jScrollPaneASDotShiftHighText.setViewportView(jTextPaneGlassDbHighText);

    jLabelASShiftTextDeclaration.setText("Text left shifted:");

    jRadioButtonASDbShiftText.setSelected(true);
    jRadioButtonASDbShiftText.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDbShiftTextItemStateChanged(evt);
      }
    });

    jScrollPaneASDotShiftlShiftText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotShiftlShiftText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassDbShiftText.setEditable(false);
    jTextPaneGlassDbShiftText.setContentType("text/html"); // NOI18N
    jTextPaneGlassDbShiftText.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jTextPaneGlassDbShiftText.setPreferredSize(new java.awt.Dimension(66, 20));
    jScrollPaneASDotShiftlShiftText.setViewportView(jTextPaneGlassDbShiftText);

    jLabelASScreenTextDeclaration.setText("Text to screen code:");

    jRadioButtonASDbScreenText.setSelected(true);
    jRadioButtonASDbScreenText.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDbScreenTextItemStateChanged(evt);
      }
    });

    jScrollPaneASDotScreenText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotScreenText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneDbScreenText.setEditable(false);
    jTextPaneDbScreenText.setContentType("text/html"); // NOI18N
    jTextPaneDbScreenText.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASDotScreenText.setViewportView(jTextPaneDbScreenText);

    jLabelASPetasciiTextDeclaration.setText("Text to petascii code:");

    jRadioButtonASDbPetasciiText.setSelected(true);
    jRadioButtonASDbPetasciiText.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASDbPetasciiTextItemStateChanged(evt);
      }
    });

    jScrollPaneASDotPetasciiText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASDotPetasciiText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassDbPetasciiText.setEditable(false);
    jTextPaneGlassDbPetasciiText.setContentType("text/html"); // NOI18N
    jTextPaneGlassDbPetasciiText.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASDotPetasciiText.setViewportView(jTextPaneGlassDbPetasciiText);

    jRadioButtonASLabelNameColon.setSelected(true);
    jRadioButtonASLabelNameColon.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButtonASLabelNameColonItemStateChanged(evt);
      }
    });

    jScrollPaneASLabelNameColon.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPaneASLabelNameColon.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

    jTextPaneGlassLabelNameColon.setEditable(false);
    jTextPaneGlassLabelNameColon.setContentType("text/html"); // NOI18N
    jTextPaneGlassLabelNameColon.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <font color='black'>zzzz</font><b>:</b>\n    </p>\n  </body>\n</html>\n");
    jScrollPaneASLabelNameColon.setViewportView(jTextPaneGlassLabelNameColon);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelASStartingDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelASOriginDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelASCommentDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelASBlockCommentDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelASHighTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelASShiftTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelASScreenTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelASLabelDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASByteDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASWordDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASWordSwappedDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASTribyteDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASLongDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASAddressDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelTmpxASStackWordDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASMultiSpriteDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASNumTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASZeroTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASPetasciiTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
          .addComponent(jLabelASMonoSpriteDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jRadioButtonASStarting)
          .addComponent(jRadioButtonASOrigin)
          .addComponent(jRadioButtonASSemicolonComment)
          .addComponent(jRadioButtonASSemicolonBlockComment)
          .addComponent(jRadioButtonASLabelName)
          .addComponent(jRadioButtonASDbByte)
          .addComponent(jRadioButtonASDwWord)
          .addComponent(jRadioButtonASMacroWordSwapped)
          .addComponent(jRadioButtonASMacroTribyte)
          .addComponent(jRadioButtonASDdLong)
          .addComponent(jRadioButtonASDwAddress)
          .addComponent(jRadioButtonASMacroStackWord)
          .addComponent(jRadioButtonASByteHexMonoSprite)
          .addComponent(jRadioButtonASByteHexMultiSprite)
          .addComponent(jRadioButtonASDbText)
          .addComponent(jRadioButtonASDbNumText)
          .addComponent(jRadioButtonASDbZeroText)
          .addComponent(jRadioButtonASDbHighText)
          .addComponent(jRadioButtonASDbShiftText)
          .addComponent(jRadioButtonASDbScreenText)
          .addComponent(jRadioButtonASDbPetasciiText))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPaneASDotPetasciiText)
          .addComponent(jScrollPaneASDotScreenText)
          .addComponent(jScrollPaneASDotShiftlShiftText)
          .addComponent(jScrollPaneASDotShiftHighText)
          .addComponent(jScrollPaneASDotNullZeroText)
          .addComponent(jScrollPaneASDotTextNumText)
          .addComponent(jScrollPaneASDotText)
          .addComponent(jScrollPaneASByteHexMultiSprite)
          .addComponent(jScrollPaneASByteHexMonoSprite)
          .addComponent(jScrollPaneASDotRtaStackWord)
          .addComponent(jScrollPaneASDotAddrAddress)
          .addComponent(jScrollPaneASMacroLong)
          .addComponent(jScrollPaneASMacroTribyte, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
          .addComponent(jScrollPaneASMacroWordSwapped, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
          .addComponent(jScrollPaneASDotWord)
          .addComponent(jScrollPaneASWord)
          .addComponent(jScrollPaneASByte)
          .addComponent(jScrollPaneASSemicolonBlockComment1)
          .addComponent(jScrollPaneASSemicolonComment)
          .addComponent(jScrollPaneASAsterixOrigin1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
          .addComponent(jScrollPaneASStarting))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jRadioButtonASLabelNameColon)
          .addComponent(jRadioButtonASByteBinMonoSprite)
          .addComponent(jRadioButtonASByteBinMultiSprite))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPaneASByteBinMultiSprite, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
              .addComponent(jScrollPaneASByteBinMonoSprite, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPaneASLabelNameColon)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jRadioButtonASMacroHexMonoSprite)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPaneASMacroHexMonoSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jRadioButtonASMacroHexMultiSprite)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPaneASMacroHexMultiSprite)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jRadioButtonASMacroBinMonoSprite)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPaneASMacroBinMonoSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jRadioButtonASMacroBinMultiSprite)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPaneASMacroBinMultiSprite)))
        .addContainerGap(29, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASStartingDeclaration)
          .addComponent(jRadioButtonASStarting)
          .addComponent(jScrollPaneASStarting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(11, 11, 11)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASOriginDeclaration)
          .addComponent(jRadioButtonASOrigin)
          .addComponent(jScrollPaneASAsterixOrigin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASCommentDeclaration)
          .addComponent(jRadioButtonASSemicolonComment)
          .addComponent(jScrollPaneASSemicolonComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(12, 12, 12)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASBlockCommentDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASSemicolonBlockComment)
          .addComponent(jScrollPaneASSemicolonBlockComment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASLabelDeclaration)
          .addComponent(jRadioButtonASLabelName)
          .addComponent(jScrollPaneASByte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASLabelNameColon)
          .addComponent(jScrollPaneASLabelNameColon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASByteDeclaration)
          .addComponent(jRadioButtonASDbByte)
          .addComponent(jScrollPaneASWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASWordDeclaration)
          .addComponent(jRadioButtonASDwWord)
          .addComponent(jScrollPaneASDotWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASWordSwappedDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASMacroWordSwapped)
          .addComponent(jScrollPaneASMacroWordSwapped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASTribyteDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASMacroTribyte)
          .addComponent(jScrollPaneASMacroTribyte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(4, 4, 4)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASLongDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASDdLong)
          .addComponent(jScrollPaneASMacroLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASAddressDeclaration)
          .addComponent(jRadioButtonASDwAddress)
          .addComponent(jScrollPaneASDotAddrAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelTmpxASStackWordDeclaration)
          .addComponent(jRadioButtonASMacroStackWord)
          .addComponent(jScrollPaneASDotRtaStackWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelASMonoSpriteDeclaration)
          .addComponent(jRadioButtonASByteHexMonoSprite)
          .addComponent(jScrollPaneASByteHexMonoSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASByteBinMonoSprite)
          .addComponent(jScrollPaneASByteBinMonoSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASMacroHexMonoSprite)
          .addComponent(jScrollPaneASMacroHexMonoSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASMacroBinMonoSprite)
          .addComponent(jScrollPaneASMacroBinMonoSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelASMultiSpriteDeclaration)
          .addComponent(jRadioButtonASByteHexMultiSprite)
          .addComponent(jScrollPaneASByteHexMultiSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASByteBinMultiSprite)
          .addComponent(jScrollPaneASByteBinMultiSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASMacroHexMultiSprite)
          .addComponent(jScrollPaneASMacroHexMultiSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jRadioButtonASMacroBinMultiSprite)
          .addComponent(jScrollPaneASMacroBinMultiSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASTextDeclaration)
          .addComponent(jRadioButtonASDbText)
          .addComponent(jScrollPaneASDotText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASNumTextDeclaration)
          .addComponent(jRadioButtonASDbNumText)
          .addComponent(jScrollPaneASDotTextNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASZeroTextDeclaration)
          .addComponent(jRadioButtonASDbZeroText)
          .addComponent(jScrollPaneASDotNullZeroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASHighTextDeclaration)
          .addComponent(jRadioButtonASDbHighText)
          .addComponent(jScrollPaneASDotShiftHighText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASShiftTextDeclaration)
          .addComponent(jRadioButtonASDbShiftText)
          .addComponent(jScrollPaneASDotShiftlShiftText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASScreenTextDeclaration)
          .addComponent(jRadioButtonASDbScreenText)
          .addComponent(jScrollPaneASDotScreenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabelASPetasciiTextDeclaration)
          .addComponent(jRadioButtonASDbPetasciiText)
          .addComponent(jScrollPaneASDotPetasciiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(32, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonASLabelNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASLabelNameItemStateChanged
        option.asmLabel=Assembler.Label.NAME;
        option.asiLabel=Assembler.Label.NAME;
    }//GEN-LAST:event_jRadioButtonASLabelNameItemStateChanged

    private void jRadioButtonASDbByteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDbByteItemStateChanged
        option.asmByte=Assembler.Byte.DB_BYTE;
        option.asiByte=Assembler.Byte.DB_BYTE_H;
    }//GEN-LAST:event_jRadioButtonASDbByteItemStateChanged

    private void jRadioButtonASDwWordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDwWordItemStateChanged
        option.asmWord=Assembler.Word.DW_WORD;
        option.asiWord=Assembler.Word.DW_WORD_H;        
    }//GEN-LAST:event_jRadioButtonASDwWordItemStateChanged

    private void jRadioButtonASSemicolonCommentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASSemicolonCommentItemStateChanged
        option.asmComment=Assembler.Comment.SEMICOLON;
        option.asiComment=Assembler.Comment.SEMICOLON;
    }//GEN-LAST:event_jRadioButtonASSemicolonCommentItemStateChanged

    private void jRadioButtonASSemicolonBlockCommentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASSemicolonBlockCommentItemStateChanged
        option.asmBlockComment=Assembler.BlockComment.SEMICOLON;
        option.asiBlockComment=Assembler.BlockComment.SEMICOLON;
    }//GEN-LAST:event_jRadioButtonASSemicolonBlockCommentItemStateChanged

    private void jRadioButtonASOriginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASOriginItemStateChanged
        option.asmOrigin=Assembler.Origin.ORG;
        option.asiOrigin=Assembler.Origin.ORG_H;
    }//GEN-LAST:event_jRadioButtonASOriginItemStateChanged

    private void jRadioButtonASStartingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASStartingItemStateChanged
        option.asmStarting=Assembler.Starting.CPU_M;
        option.asiStarting=Assembler.Starting.CPU_I;
    }//GEN-LAST:event_jRadioButtonASStartingItemStateChanged

    private void jRadioButtonASByteHexMonoSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASByteHexMonoSpriteItemStateChanged
        option.glassMonoSprite=Assembler.MonoSprite.BYTE_HEX;
    }//GEN-LAST:event_jRadioButtonASByteHexMonoSpriteItemStateChanged

    private void jRadioButtonASByteHexMultiSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASByteHexMultiSpriteItemStateChanged
        option.glassMultiSprite=Assembler.MultiSprite.BYTE_HEX;
    }//GEN-LAST:event_jRadioButtonASByteHexMultiSpriteItemStateChanged

    private void jRadioButtonASByteBinMonoSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASByteBinMonoSpriteItemStateChanged
        option.glassMonoSprite=Assembler.MonoSprite.BYTE_BIN;
    }//GEN-LAST:event_jRadioButtonASByteBinMonoSpriteItemStateChanged

    private void jRadioButtonASByteBinMultiSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASByteBinMultiSpriteItemStateChanged
        option.glassMultiSprite=Assembler.MultiSprite.BYTE_BIN;
    }//GEN-LAST:event_jRadioButtonASByteBinMultiSpriteItemStateChanged

    private void jRadioButtonASMacroHexMonoSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASMacroHexMonoSpriteItemStateChanged
        option.glassMonoSprite=Assembler.MonoSprite.MACRO5_HEX;
    }//GEN-LAST:event_jRadioButtonASMacroHexMonoSpriteItemStateChanged

    private void jRadioButtonASMacroHexMultiSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASMacroHexMultiSpriteItemStateChanged
        option.glassMultiSprite=Assembler.MultiSprite.MACRO5_HEX;
    }//GEN-LAST:event_jRadioButtonASMacroHexMultiSpriteItemStateChanged

    private void jRadioButtonASMacroBinMonoSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASMacroBinMonoSpriteItemStateChanged
        option.glassMonoSprite=Assembler.MonoSprite.MACRO5_BIN;
    }//GEN-LAST:event_jRadioButtonASMacroBinMonoSpriteItemStateChanged

    private void jRadioButtonASMacroBinMultiSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASMacroBinMultiSpriteItemStateChanged
        option.glassMultiSprite=Assembler.MultiSprite.MACRO5_BIN;
    }//GEN-LAST:event_jRadioButtonASMacroBinMultiSpriteItemStateChanged

    private void jRadioButtonASMacroTribyteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASMacroTribyteItemStateChanged
        option.asmTribyte=Assembler.Tribyte.MACRO6_TRIBYTE;
        option.asiTribyte=Assembler.Tribyte.MACRO6_TRIBYTE;
    }//GEN-LAST:event_jRadioButtonASMacroTribyteItemStateChanged

    private void jRadioButtonASDdLongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDdLongItemStateChanged
        option.asmLong=Assembler.Long.DD_LONG;
        option.asiLong=Assembler.Long.DD_LONG_H;
    }//GEN-LAST:event_jRadioButtonASDdLongItemStateChanged

    private void jRadioButtonASMacroWordSwappedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASMacroWordSwappedItemStateChanged
        option.asmWordSwapped=Assembler.WordSwapped.MACRO6_WORD_SWAPPED;
        option.asiWordSwapped=Assembler.WordSwapped.MACRO6_WORD_SWAPPED;
    }//GEN-LAST:event_jRadioButtonASMacroWordSwappedItemStateChanged

    private void jRadioButtonASDbTextItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDbTextItemStateChanged
        option.asmText=Assembler.Text.DB_BYTE_TEXT;
        option.asiText=Assembler.Text.DB_BYTE_TEXT;
    }//GEN-LAST:event_jRadioButtonASDbTextItemStateChanged

    private void jRadioButtonASDbNumTextItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDbNumTextItemStateChanged
        option.asmNumText=Assembler.NumText.DB_BYTE_NUMTEXT;
        option.asiNumText=Assembler.NumText.DB_BYTE_NUMTEXT;
    }//GEN-LAST:event_jRadioButtonASDbNumTextItemStateChanged

    private void jRadioButtonASDbZeroTextItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDbZeroTextItemStateChanged
        option.asmZeroText=Assembler.ZeroText.DB_BYTE_ZEROTEXT;
        option.asiZeroText=Assembler.ZeroText.DB_BYTE_ZEROTEXT;
    }//GEN-LAST:event_jRadioButtonASDbZeroTextItemStateChanged

    private void jRadioButtonASDwAddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDwAddressItemStateChanged
        option.asmAddress=Assembler.Address.DW_ADDR;
        option.asiAddress=Assembler.Address.DW_ADDR_H;
    }//GEN-LAST:event_jRadioButtonASDwAddressItemStateChanged

    private void jRadioButtonASMacroStackWordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASMacroStackWordItemStateChanged
        option.asmStackWord=Assembler.StackWord.MACRO5_STACKWORD;
        option.asiStackWord=Assembler.StackWord.MACRO5_STACKWORD;
    }//GEN-LAST:event_jRadioButtonASMacroStackWordItemStateChanged

    private void jRadioButtonASDbHighTextItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDbHighTextItemStateChanged
        option.asmHighText=Assembler.HighText.DB_BYTE_HIGHTEXT;
        option.asiHighText=Assembler.HighText.DB_BYTE_HIGHTEXT;
    }//GEN-LAST:event_jRadioButtonASDbHighTextItemStateChanged

    private void jRadioButtonASDbShiftTextItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDbShiftTextItemStateChanged
        option.asmShiftText=Assembler.ShiftText.DB_BYTE_SHIFTTEXT;
        option.asiShiftText=Assembler.ShiftText.DB_BYTE_SHIFTTEXT;
    }//GEN-LAST:event_jRadioButtonASDbShiftTextItemStateChanged

    private void jRadioButtonASDbScreenTextItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDbScreenTextItemStateChanged
        option.asmScreenText=Assembler.ScreenText.DB_BYTE_SCREENTEXT;
        option.asiScreenText=Assembler.ScreenText.DB_BYTE_SCREENTEXT;
    }//GEN-LAST:event_jRadioButtonASDbScreenTextItemStateChanged

    private void jRadioButtonASDbPetasciiTextItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASDbPetasciiTextItemStateChanged
        option.asmPetasciiText=Assembler.PetasciiText.DB_BYTE_PETASCIITEXT;
        option.asiPetasciiText=Assembler.PetasciiText.DB_BYTE_PETASCIITEXT;
    }//GEN-LAST:event_jRadioButtonASDbPetasciiTextItemStateChanged

    private void jRadioButtonASLabelNameColonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonASLabelNameColonItemStateChanged
        option.asmLabel=Assembler.Label.NAME_COLON;
        option.asiLabel=Assembler.Label.NAME_COLON;
    }//GEN-LAST:event_jRadioButtonASLabelNameColonItemStateChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextPane TmpxPaneGlassByteHexMultiSprite;
  private javax.swing.JLabel jLabelASAddressDeclaration;
  private javax.swing.JLabel jLabelASBlockCommentDeclaration;
  private javax.swing.JLabel jLabelASByteDeclaration;
  private javax.swing.JLabel jLabelASCommentDeclaration;
  private javax.swing.JLabel jLabelASHighTextDeclaration;
  private javax.swing.JLabel jLabelASLabelDeclaration;
  private javax.swing.JLabel jLabelASLongDeclaration;
  private javax.swing.JLabel jLabelASMonoSpriteDeclaration;
  private javax.swing.JLabel jLabelASMultiSpriteDeclaration;
  private javax.swing.JLabel jLabelASNumTextDeclaration;
  private javax.swing.JLabel jLabelASOriginDeclaration;
  private javax.swing.JLabel jLabelASPetasciiTextDeclaration;
  private javax.swing.JLabel jLabelASScreenTextDeclaration;
  private javax.swing.JLabel jLabelASShiftTextDeclaration;
  private javax.swing.JLabel jLabelASStartingDeclaration;
  private javax.swing.JLabel jLabelASTextDeclaration;
  private javax.swing.JLabel jLabelASTribyteDeclaration;
  private javax.swing.JLabel jLabelASWordDeclaration;
  private javax.swing.JLabel jLabelASWordSwappedDeclaration;
  private javax.swing.JLabel jLabelASZeroTextDeclaration;
  private javax.swing.JLabel jLabelTmpxASStackWordDeclaration;
  private javax.swing.JRadioButton jRadioButtonASByteBinMonoSprite;
  private javax.swing.JRadioButton jRadioButtonASByteBinMultiSprite;
  private javax.swing.JRadioButton jRadioButtonASByteHexMonoSprite;
  private javax.swing.JRadioButton jRadioButtonASByteHexMultiSprite;
  private javax.swing.JRadioButton jRadioButtonASDbByte;
  private javax.swing.JRadioButton jRadioButtonASDbHighText;
  private javax.swing.JRadioButton jRadioButtonASDbNumText;
  private javax.swing.JRadioButton jRadioButtonASDbPetasciiText;
  private javax.swing.JRadioButton jRadioButtonASDbScreenText;
  private javax.swing.JRadioButton jRadioButtonASDbShiftText;
  private javax.swing.JRadioButton jRadioButtonASDbText;
  private javax.swing.JRadioButton jRadioButtonASDbZeroText;
  private javax.swing.JRadioButton jRadioButtonASDdLong;
  private javax.swing.JRadioButton jRadioButtonASDwAddress;
  private javax.swing.JRadioButton jRadioButtonASDwWord;
  private javax.swing.JRadioButton jRadioButtonASLabelName;
  private javax.swing.JRadioButton jRadioButtonASLabelNameColon;
  private javax.swing.JRadioButton jRadioButtonASMacroBinMonoSprite;
  private javax.swing.JRadioButton jRadioButtonASMacroBinMultiSprite;
  private javax.swing.JRadioButton jRadioButtonASMacroHexMonoSprite;
  private javax.swing.JRadioButton jRadioButtonASMacroHexMultiSprite;
  private javax.swing.JRadioButton jRadioButtonASMacroStackWord;
  private javax.swing.JRadioButton jRadioButtonASMacroTribyte;
  private javax.swing.JRadioButton jRadioButtonASMacroWordSwapped;
  private javax.swing.JRadioButton jRadioButtonASOrigin;
  private javax.swing.JRadioButton jRadioButtonASSemicolonBlockComment;
  private javax.swing.JRadioButton jRadioButtonASSemicolonComment;
  private javax.swing.JRadioButton jRadioButtonASStarting;
  private javax.swing.JScrollPane jScrollPaneASAsterixOrigin1;
  private javax.swing.JScrollPane jScrollPaneASByte;
  private javax.swing.JScrollPane jScrollPaneASByteBinMonoSprite;
  private javax.swing.JScrollPane jScrollPaneASByteBinMultiSprite;
  private javax.swing.JScrollPane jScrollPaneASByteHexMonoSprite;
  private javax.swing.JScrollPane jScrollPaneASByteHexMultiSprite;
  private javax.swing.JScrollPane jScrollPaneASDotAddrAddress;
  private javax.swing.JScrollPane jScrollPaneASDotNullZeroText;
  private javax.swing.JScrollPane jScrollPaneASDotPetasciiText;
  private javax.swing.JScrollPane jScrollPaneASDotRtaStackWord;
  private javax.swing.JScrollPane jScrollPaneASDotScreenText;
  private javax.swing.JScrollPane jScrollPaneASDotShiftHighText;
  private javax.swing.JScrollPane jScrollPaneASDotShiftlShiftText;
  private javax.swing.JScrollPane jScrollPaneASDotText;
  private javax.swing.JScrollPane jScrollPaneASDotTextNumText;
  private javax.swing.JScrollPane jScrollPaneASDotWord;
  private javax.swing.JScrollPane jScrollPaneASLabelNameColon;
  private javax.swing.JScrollPane jScrollPaneASMacroBinMonoSprite;
  private javax.swing.JScrollPane jScrollPaneASMacroBinMultiSprite;
  private javax.swing.JScrollPane jScrollPaneASMacroHexMonoSprite;
  private javax.swing.JScrollPane jScrollPaneASMacroHexMultiSprite;
  private javax.swing.JScrollPane jScrollPaneASMacroLong;
  private javax.swing.JScrollPane jScrollPaneASMacroTribyte;
  private javax.swing.JScrollPane jScrollPaneASMacroWordSwapped;
  private javax.swing.JScrollPane jScrollPaneASSemicolonBlockComment1;
  private javax.swing.JScrollPane jScrollPaneASSemicolonComment;
  private javax.swing.JScrollPane jScrollPaneASStarting;
  private javax.swing.JScrollPane jScrollPaneASWord;
  private javax.swing.JTextPane jTextPaneASDbByte;
  private javax.swing.JTextPane jTextPaneASDwWord;
  private javax.swing.JTextPane jTextPaneASOrigin;
  private javax.swing.JTextPane jTextPaneASSemicolonComment;
  private javax.swing.JTextPane jTextPaneASStarting;
  private javax.swing.JTextPane jTextPaneDbScreenText;
  private javax.swing.JTextPane jTextPaneGlassByteBinMonoSprite;
  private javax.swing.JTextPane jTextPaneGlassByteBinMultiSprite;
  private javax.swing.JTextPane jTextPaneGlassByteHexMonoSprite;
  private javax.swing.JTextPane jTextPaneGlassDbHighText;
  private javax.swing.JTextPane jTextPaneGlassDbNumText;
  private javax.swing.JTextPane jTextPaneGlassDbPetasciiText;
  private javax.swing.JTextPane jTextPaneGlassDbShiftText;
  private javax.swing.JTextPane jTextPaneGlassDbText;
  private javax.swing.JTextPane jTextPaneGlassDbZeroText;
  private javax.swing.JTextPane jTextPaneGlassDwAddress;
  private javax.swing.JTextPane jTextPaneGlassLabelName;
  private javax.swing.JTextPane jTextPaneGlassLabelNameColon;
  private javax.swing.JTextPane jTextPaneGlassMacroBinMonoSprite;
  private javax.swing.JTextPane jTextPaneGlassMacroBinMultiSprite;
  private javax.swing.JTextPane jTextPaneGlassMacroHexMonoSprite;
  private javax.swing.JTextPane jTextPaneGlassMacroHexMultiSprite;
  private javax.swing.JTextPane jTextPaneGlassMacroLong;
  private javax.swing.JTextPane jTextPaneGlassMacroStackWord;
  private javax.swing.JTextPane jTextPaneGlassMacroTribyte;
  private javax.swing.JTextPane jTextPaneGlassMacroWordSwapped;
  private javax.swing.JTextPane jTextPaneTmpxSemicolonBlockComment1;
  // End of variables declaration//GEN-END:variables
}
