/**
 * @(#)JFrameDisassembler.java 2019/12/01
 *
 * ICE Team free software group
 *
 * This file is part of C64 Java Software Emulator.
 * See README for copyright notice.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 *  02111-1307  USA.
 */
package sw_emulator.swing;

import java.awt.Point;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.Caret;
import javax.swing.text.Utilities;
import org.fife.rsta.ui.search.FindDialog;
import org.fife.rsta.ui.search.SearchEvent;
import org.fife.rsta.ui.search.SearchListener;
import org.fife.ui.rtextarea.SearchContext;
import org.fife.ui.rtextarea.SearchEngine;
import org.fife.ui.rtextarea.SearchResult;
import sw_emulator.software.Disassembly;
import sw_emulator.software.MemoryDasm;
import sw_emulator.software.memory.memoryState;
import sw_emulator.swing.main.FileManager;
import sw_emulator.swing.main.Option;
import sw_emulator.swing.main.Project;
import sw_emulator.swing.main.userAction;
import sw_emulator.swing.table.DataTableModelMemory;
import sw_emulator.swing.table.MemoryTableCellRenderer;

/**
 * Main frame for C64 disassembler
 * 
 * @author ice
 */
public class JDisassemblerFrame extends javax.swing.JFrame implements userAction {
  /** Option to use */
  Option option=new Option();
  
  /** Project to use */
  Project project;
  
  /** Project file name */
  File projectFile;
  
  /** Last saved project values */
  Project savedProject;
  
  /** Data table for memory */
  DataTableModelMemory dataTableModelMemory=new DataTableModelMemory();
  
  /** Disassembly engine  */
  Disassembly disassembly=new Disassembly();
  
  /** Option dialog */
  JOptionDialog jOptionDialog=new JOptionDialog(this, true);
  
  /** Project dialog */
  JProjectDialog jProjectDialog=new JProjectDialog(this, true);
  
  /** Project chhoser file dialog*/
  JFileChooser projectChooserFile=new JFileChooser();
  
  /** Export as file chooser */
  JFileChooser exportAsChooserFile=new JFileChooser();
  
  /** Memory cell renderer for table */
  MemoryTableCellRenderer memoryTableCellRenderer=new MemoryTableCellRenderer();
  
  /** License dialog */
  JLicenseDialog jLicenseDialog=new JLicenseDialog(this, true);
  
  /** Credit dialog */
  JCreditsDialog jCreditsDialog=new JCreditsDialog(this, true);
  
  /** About dialog */
  JAboutDialog jAboutDialog=new JAboutDialog(this, true);
  
  /** Help dialog */
  JHelpFrame jHelpFrame=new JHelpFrame();
  
  /** Find dialòg for source */
  FindDialog findDialogSource;
  
  /** Find dialog for disassembly */
  FindDialog findDialogDis;
  
  
    /**
     * Creates new form JFrameDisassembler
     */
    public JDisassemblerFrame() {
        initComponents();
        
        FileManager.instance.readOptionFile(FileManager.optionFile, option);
        jOptionDialog.useOption(option);
        
        projectChooserFile.addChoosableFileFilter(new FileNameExtensionFilter("JC64Dis", "dis"));
        exportAsChooserFile.addChoosableFileFilter(new FileNameExtensionFilter("Source","txt"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jButtonNewProject = new javax.swing.JButton();
        jButtonOpenProject = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtonSaveProject = new javax.swing.JButton();
        jButtonSaveProjectAs = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jSeparatorButton1 = new javax.swing.JToolBar.Separator();
        jButtonClearDMem = new javax.swing.JButton();
        jButtonClearUMem = new javax.swing.JButton();
        jButtonClearUMem1 = new javax.swing.JButton();
        jButtonClearUMem2 = new javax.swing.JButton();
        jButtonMarkCode = new javax.swing.JButton();
        jButtonMarkData = new javax.swing.JButton();
        jSeparatorButton3 = new javax.swing.JToolBar.Separator();
        jButtonConfigure = new javax.swing.JButton();
        jButtonSIDLD = new javax.swing.JButton();
        jButtonViewProject = new javax.swing.JButton();
        jSeparatorButton2 = new javax.swing.JToolBar.Separator();
        jButtonDisassemble = new javax.swing.JButton();
        jButtonFindDis = new javax.swing.JButton();
        jButtonExportAsDiss = new javax.swing.JButton();
        jButtonFindSource = new javax.swing.JButton();
        jButtonExportAsSource = new javax.swing.JButton();
        jSplitPaneExternal = new javax.swing.JSplitPane();
        jSplitPaneInternal = new javax.swing.JSplitPane();
        jScrollPaneLeft = new javax.swing.JScrollPane();
        rSyntaxTextAreaDis = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        jScrollPaneRight = new javax.swing.JScrollPane();
        rSyntaxTextAreaSource = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        jScrollPaneMemory = new javax.swing.JScrollPane();
        jTableMemory = new javax.swing.JTable() {

            //Implement table cell tool tips.
            public String getToolTipText(MouseEvent e) {
                String tip = null;
                java.awt.Point p = e.getPoint();
                int rowIndex = rowAtPoint(p);
                int colIndex = columnAtPoint(p);
                int realColumnIndex = convertColumnIndexToModel(colIndex);

                try {
                    MemoryDasm memory=dataTableModelMemory.getData()[rowIndex];
                    switch (dataTableModelMemory.columns[realColumnIndex]) {
                        case ID:
                        if (!memory.isInside) tip="Memory outside of the program";
                        else if(memory.isCode) tip="Memory marked as code";
                        else if (memory.isData) tip="Memory marked as data";
                        else tip="Memory not marked as code or data";
                        break;
                        case DC:
                        if ((Boolean)getValueAt(rowIndex, colIndex)) tip=memory.dasmComment;
                        break;
                        case UC:
                        if ((Boolean)getValueAt(rowIndex, colIndex)) tip=memory.userComment;
                        break;
                        case DL:
                        if ((Boolean)getValueAt(rowIndex, colIndex)) tip=memory.dasmLocation;
                        break;
                        case UL:
                        if ((Boolean)getValueAt(rowIndex, colIndex)) tip=memory.userLocation;
                        break;
                    }
                } catch (RuntimeException e1) {
                    //catch null pointer exception if mouse is over an empty line
                }
                return tip;
            }

        };
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemNewProject = new javax.swing.JMenuItem();
        jSeparatorProject1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemOpenProject = new javax.swing.JMenuItem();
        jMenuItemCloseProject = new javax.swing.JMenuItem();
        jSeparatorProject2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSaveProject = new javax.swing.JMenuItem();
        jMenuItemSaveAsProject = new javax.swing.JMenuItem();
        jSeparatorProject3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuMarkCode = new javax.swing.JMenu();
        jMenuItemClearDMem = new javax.swing.JMenuItem();
        jMenuItemClearUMem = new javax.swing.JMenuItem();
        jMenuItemAddComment = new javax.swing.JMenuItem();
        jMenuItemUserLabel = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMarkCode = new javax.swing.JMenuItem();
        jMenuItemMarkData = new javax.swing.JMenuItem();
        jMenuOption = new javax.swing.JMenu();
        jMenuItemConfigure = new javax.swing.JMenuItem();
        jMenuItemSIDLD = new javax.swing.JMenuItem();
        jSeparatorOption = new javax.swing.JPopupMenu.Separator();
        jMenuItemViewProject = new javax.swing.JMenuItem();
        jMenuSource = new javax.swing.JMenu();
        jMenuItemDiss = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFindDis = new javax.swing.JMenuItem();
        jMenuItemDissSaveAs = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFindSource = new javax.swing.JMenuItem();
        jMenuItemSourceSaveAs = new javax.swing.JMenuItem();
        jMenuHelpContents = new javax.swing.JMenu();
        jMenuItemContents = new javax.swing.JMenuItem();
        jSeparatorHelp1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLicense = new javax.swing.JMenuItem();
        jMenuItemCredits = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JC64Dis");

        jToolBar.setFloatable(false);
        jToolBar.setRollover(true);

        jButtonNewProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/filenew.png"))); // NOI18N
        jButtonNewProject.setToolTipText("New project");
        jButtonNewProject.setFocusable(false);
        jButtonNewProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewProjectActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonNewProject);

        jButtonOpenProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/fileopen.png"))); // NOI18N
        jButtonOpenProject.setToolTipText("Open project");
        jButtonOpenProject.setFocusable(false);
        jButtonOpenProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOpenProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonOpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenProjectActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonOpenProject);

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/close.png"))); // NOI18N
        jButtonClose.setToolTipText("Close the project");
        jButtonClose.setFocusable(false);
        jButtonClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonClose);

        jButtonSaveProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/filesave.png"))); // NOI18N
        jButtonSaveProject.setToolTipText("Save project");
        jButtonSaveProject.setFocusable(false);
        jButtonSaveProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaveProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSaveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveProjectActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonSaveProject);

        jButtonSaveProjectAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/filesaveas.png"))); // NOI18N
        jButtonSaveProjectAs.setToolTipText("Save project as");
        jButtonSaveProjectAs.setFocusable(false);
        jButtonSaveProjectAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaveProjectAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSaveProjectAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveProjectAsActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonSaveProjectAs);

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/exit.png"))); // NOI18N
        jButtonExit.setToolTipText("Save project as");
        jButtonExit.setFocusable(false);
        jButtonExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonExit);
        jToolBar.add(jSeparatorButton1);

        jButtonClearDMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/eraser.png"))); // NOI18N
        jButtonClearDMem.setToolTipText("Esase dasm automatic comment");
        jButtonClearDMem.setFocusable(false);
        jButtonClearDMem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClearDMem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClearDMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearDMemActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonClearDMem);

        jButtonClearUMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/eraser1.png"))); // NOI18N
        jButtonClearUMem.setToolTipText("Erase user comment");
        jButtonClearUMem.setFocusable(false);
        jButtonClearUMem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClearUMem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClearUMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearUMemActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonClearUMem);

        jButtonClearUMem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/comm.png"))); // NOI18N
        jButtonClearUMem1.setToolTipText("Add user comment");
        jButtonClearUMem1.setFocusable(false);
        jButtonClearUMem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClearUMem1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClearUMem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearUMem1ActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonClearUMem1);

        jButtonClearUMem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mem2.png"))); // NOI18N
        jButtonClearUMem2.setToolTipText("Add user label");
        jButtonClearUMem2.setFocusable(false);
        jButtonClearUMem2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClearUMem2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClearUMem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearUMem2ActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonClearUMem2);

        jButtonMarkCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/code.png"))); // NOI18N
        jButtonMarkCode.setToolTipText("Mark the selected addresses as code");
        jButtonMarkCode.setFocusable(false);
        jButtonMarkCode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMarkCode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMarkCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarkCodeActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonMarkCode);

        jButtonMarkData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/data.png"))); // NOI18N
        jButtonMarkData.setToolTipText("Mark the selected addresses as data");
        jButtonMarkData.setFocusable(false);
        jButtonMarkData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMarkData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMarkData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarkDataActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonMarkData);
        jToolBar.add(jSeparatorButton3);

        jButtonConfigure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/configure.png"))); // NOI18N
        jButtonConfigure.setToolTipText("Set general option");
        jButtonConfigure.setFocusable(false);
        jButtonConfigure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConfigure.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigureActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonConfigure);

        jButtonSIDLD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mem.png"))); // NOI18N
        jButtonSIDLD.setToolTipText("Apply SIDLD flags to memory");
        jButtonSIDLD.setFocusable(false);
        jButtonSIDLD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSIDLD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSIDLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIDLDActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonSIDLD);

        jButtonViewProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/view_detailed.png"))); // NOI18N
        jButtonViewProject.setToolTipText("View project");
        jButtonViewProject.setFocusable(false);
        jButtonViewProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonViewProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonViewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewProjectActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonViewProject);
        jToolBar.add(jSeparatorButton2);

        jButtonDisassemble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/exec.png"))); // NOI18N
        jButtonDisassemble.setToolTipText("Disassemble");
        jButtonDisassemble.setFocusable(false);
        jButtonDisassemble.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDisassemble.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDisassemble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisassembleActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonDisassemble);

        jButtonFindDis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/findd.png"))); // NOI18N
        jButtonFindDis.setToolTipText("Find a text in preview");
        jButtonFindDis.setFocusable(false);
        jButtonFindDis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFindDis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFindDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindDisActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonFindDis);

        jButtonExportAsDiss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/exportas1.png"))); // NOI18N
        jButtonExportAsDiss.setToolTipText("Save preview file");
        jButtonExportAsDiss.setFocusable(false);
        jButtonExportAsDiss.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExportAsDiss.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExportAsDiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportAsDissActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonExportAsDiss);

        jButtonFindSource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/finds.png"))); // NOI18N
        jButtonFindSource.setToolTipText("Find a text in source");
        jButtonFindSource.setFocusable(false);
        jButtonFindSource.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFindSource.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFindSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindSourceActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonFindSource);

        jButtonExportAsSource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/exportas2.png"))); // NOI18N
        jButtonExportAsSource.setToolTipText("Save source file");
        jButtonExportAsSource.setFocusable(false);
        jButtonExportAsSource.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExportAsSource.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExportAsSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportAsSourceActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonExportAsSource);

        jSplitPaneExternal.setToolTipText("");

        jSplitPaneInternal.setResizeWeight(0.5);
        jSplitPaneInternal.setToolTipText("");

        rSyntaxTextAreaDis.setEditable(false);
        rSyntaxTextAreaDis.setColumns(20);
        rSyntaxTextAreaDis.setRows(5);
        rSyntaxTextAreaDis.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        rSyntaxTextAreaDis.setSyntaxEditingStyle("text/asm6502");
        findDialogDis=new FindDialog(this, new SearchListener() {
            @Override
            public void searchEvent(SearchEvent e) {
                SearchEvent.Type type = e.getType();
                SearchContext context = e.getSearchContext();
                SearchResult result;

                switch (type) {
                    default: // Prevent FindBugs warning later
                    case MARK_ALL:
                    result = SearchEngine.markAll(rSyntaxTextAreaDis, context);
                    break;
                    case FIND:
                    result = SearchEngine.find(rSyntaxTextAreaDis, context);
                    if (!result.wasFound()) {
                        UIManager.getLookAndFeel().provideErrorFeedback(rSyntaxTextAreaDis);
                    }
                    break;
                }

            }

            @Override
            public String getSelectedText() {
                return rSyntaxTextAreaDis.getSelectedText();
            }
        }
    );
    rSyntaxTextAreaDis.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            rSyntaxTextAreaDisMouseClicked(evt);
        }
    });
    jScrollPaneLeft.setViewportView(rSyntaxTextAreaDis);

    jSplitPaneInternal.setLeftComponent(jScrollPaneLeft);

    rSyntaxTextAreaSource.setEditable(false);
    rSyntaxTextAreaSource.setColumns(20);
    rSyntaxTextAreaSource.setRows(5);
    rSyntaxTextAreaSource.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
    rSyntaxTextAreaSource.setSyntaxEditingStyle("text/asm6502");
    findDialogSource=new FindDialog(this, new SearchListener() {
        @Override
        public void searchEvent(SearchEvent e) {
            SearchEvent.Type type = e.getType();
            SearchContext context = e.getSearchContext();
            SearchResult result;

            switch (type) {
                default: // Prevent FindBugs warning later
                case MARK_ALL:
                result = SearchEngine.markAll(rSyntaxTextAreaSource, context);
                break;
                case FIND:
                result = SearchEngine.find(rSyntaxTextAreaSource, context);
                if (!result.wasFound()) {
                    UIManager.getLookAndFeel().provideErrorFeedback(rSyntaxTextAreaSource);
                }
                break;
            }

        }

        @Override
        public String getSelectedText() {
            return rSyntaxTextAreaSource.getSelectedText();
        }
    }
    );
    jScrollPaneRight.setViewportView(rSyntaxTextAreaSource);

    jSplitPaneInternal.setRightComponent(jScrollPaneRight);

    jSplitPaneExternal.setRightComponent(jSplitPaneInternal);

    jScrollPaneMemory.setPreferredSize(new java.awt.Dimension(150, 403));

    jTableMemory.setModel(dataTableModelMemory);
    jTableMemory.setDefaultRenderer(Integer.class, memoryTableCellRenderer);
    jScrollPaneMemory.setViewportView(jTableMemory);

    jSplitPaneExternal.setLeftComponent(jScrollPaneMemory);

    jMenuFile.setText("File");

    jMenuItemNewProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemNewProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/filenew.png"))); // NOI18N
    jMenuItemNewProject.setMnemonic('w');
    jMenuItemNewProject.setText("New Project");
    jMenuItemNewProject.setToolTipText("");
    jMenuItemNewProject.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemNewProjectActionPerformed(evt);
        }
    });
    jMenuFile.add(jMenuItemNewProject);
    jMenuFile.add(jSeparatorProject1);

    jMenuItemOpenProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemOpenProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/fileopen.png"))); // NOI18N
    jMenuItemOpenProject.setMnemonic('e');
    jMenuItemOpenProject.setText("Open Project");
    jMenuItemOpenProject.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemOpenProjectActionPerformed(evt);
        }
    });
    jMenuFile.add(jMenuItemOpenProject);

    jMenuItemCloseProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemCloseProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/close.png"))); // NOI18N
    jMenuItemCloseProject.setMnemonic('c');
    jMenuItemCloseProject.setText("Close Project");
    jMenuItemCloseProject.setToolTipText("");
    jMenuItemCloseProject.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemCloseProjectActionPerformed(evt);
        }
    });
    jMenuFile.add(jMenuItemCloseProject);
    jMenuFile.add(jSeparatorProject2);

    jMenuItemSaveProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemSaveProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/filesave.png"))); // NOI18N
    jMenuItemSaveProject.setMnemonic('s');
    jMenuItemSaveProject.setText("Save Project");
    jMenuItemSaveProject.setToolTipText("");
    jMenuItemSaveProject.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemSaveProjectActionPerformed(evt);
        }
    });
    jMenuFile.add(jMenuItemSaveProject);

    jMenuItemSaveAsProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/filesaveas.png"))); // NOI18N
    jMenuItemSaveAsProject.setMnemonic('v');
    jMenuItemSaveAsProject.setText("Save Project As");
    jMenuItemSaveAsProject.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemSaveAsProjectActionPerformed(evt);
        }
    });
    jMenuFile.add(jMenuItemSaveAsProject);
    jMenuFile.add(jSeparatorProject3);

    jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/exit.png"))); // NOI18N
    jMenuItemExit.setMnemonic('x');
    jMenuItemExit.setText("Exit");
    jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemExitActionPerformed(evt);
        }
    });
    jMenuFile.add(jMenuItemExit);

    jMenuBar.add(jMenuFile);

    jMenuMarkCode.setText("Memory");

    jMenuItemClearDMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/eraser.png"))); // NOI18N
    jMenuItemClearDMem.setText("Clear dasm automatic comment");
    jMenuItemClearDMem.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemClearDMemActionPerformed(evt);
        }
    });
    jMenuMarkCode.add(jMenuItemClearDMem);

    jMenuItemClearUMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/eraser1.png"))); // NOI18N
    jMenuItemClearUMem.setText("Clear user comment");
    jMenuItemClearUMem.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemClearUMemActionPerformed(evt);
        }
    });
    jMenuMarkCode.add(jMenuItemClearUMem);

    jMenuItemAddComment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/comm.png"))); // NOI18N
    jMenuItemAddComment.setText("Add user comment");
    jMenuItemAddComment.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemAddCommentActionPerformed(evt);
        }
    });
    jMenuMarkCode.add(jMenuItemAddComment);

    jMenuItemUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/mem2.png"))); // NOI18N
    jMenuItemUserLabel.setText("Add user label");
    jMenuItemUserLabel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemUserLabelActionPerformed(evt);
        }
    });
    jMenuMarkCode.add(jMenuItemUserLabel);
    jMenuMarkCode.add(jSeparator3);

    jMenuItemMarkCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/code.png"))); // NOI18N
    jMenuItemMarkCode.setText("Mark as code");
    jMenuItemMarkCode.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMarkCodeActionPerformed(evt);
        }
    });
    jMenuMarkCode.add(jMenuItemMarkCode);

    jMenuItemMarkData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/data.png"))); // NOI18N
    jMenuItemMarkData.setText("Mark as data");
    jMenuItemMarkData.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMarkDataActionPerformed(evt);
        }
    });
    jMenuMarkCode.add(jMenuItemMarkData);

    jMenuBar.add(jMenuMarkCode);

    jMenuOption.setText("Option");
    jMenuOption.setToolTipText("");

    jMenuItemConfigure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/configure.png"))); // NOI18N
    jMenuItemConfigure.setMnemonic('o');
    jMenuItemConfigure.setText("General Option");
    jMenuItemConfigure.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemConfigureActionPerformed(evt);
        }
    });
    jMenuOption.add(jMenuItemConfigure);

    jMenuItemSIDLD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/mem.png"))); // NOI18N
    jMenuItemSIDLD.setText("Apply SIDLD flags to memory");
    jMenuItemSIDLD.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemSIDLDActionPerformed(evt);
        }
    });
    jMenuOption.add(jMenuItemSIDLD);
    jMenuOption.add(jSeparatorOption);

    jMenuItemViewProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/view_detailed.png"))); // NOI18N
    jMenuItemViewProject.setMnemonic('v');
    jMenuItemViewProject.setText("View Project");
    jMenuItemViewProject.setToolTipText("");
    jMenuItemViewProject.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemViewProjectActionPerformed(evt);
        }
    });
    jMenuOption.add(jMenuItemViewProject);

    jMenuBar.add(jMenuOption);

    jMenuSource.setText("Source");

    jMenuItemDiss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/exec.png"))); // NOI18N
    jMenuItemDiss.setText("Disassemble");
    jMenuItemDiss.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDissActionPerformed(evt);
        }
    });
    jMenuSource.add(jMenuItemDiss);
    jMenuSource.add(jSeparator1);

    jMenuItemFindDis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/findd.png"))); // NOI18N
    jMenuItemFindDis.setText("Find text in preview");
    jMenuItemFindDis.setToolTipText("");
    jMenuItemFindDis.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemFindDisActionPerformed(evt);
        }
    });
    jMenuSource.add(jMenuItemFindDis);

    jMenuItemDissSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/exportas1.png"))); // NOI18N
    jMenuItemDissSaveAs.setText("Export As of preview");
    jMenuItemDissSaveAs.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDissSaveAsActionPerformed(evt);
        }
    });
    jMenuSource.add(jMenuItemDissSaveAs);
    jMenuSource.add(jSeparator2);

    jMenuItemFindSource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/finds.png"))); // NOI18N
    jMenuItemFindSource.setText("Find text in source");
    jMenuItemFindSource.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemFindSourceActionPerformed(evt);
        }
    });
    jMenuSource.add(jMenuItemFindSource);

    jMenuItemSourceSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/exportas2.png"))); // NOI18N
    jMenuItemSourceSaveAs.setText("Export As of source");
    jMenuItemSourceSaveAs.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemSourceSaveAsActionPerformed(evt);
        }
    });
    jMenuSource.add(jMenuItemSourceSaveAs);

    jMenuBar.add(jMenuSource);

    jMenuHelpContents.setText("Help");

    jMenuItemContents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sw_emulator/swing/icons/mini/help_index.png"))); // NOI18N
    jMenuItemContents.setText("Help contents");
    jMenuItemContents.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemContentsActionPerformed(evt);
        }
    });
    jMenuHelpContents.add(jMenuItemContents);
    jMenuHelpContents.add(jSeparatorHelp1);

    jMenuItemLicense.setText("License");
    jMenuItemLicense.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemLicenseActionPerformed(evt);
        }
    });
    jMenuHelpContents.add(jMenuItemLicense);

    jMenuItemCredits.setText("Credits");
    jMenuItemCredits.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemCreditsActionPerformed(evt);
        }
    });
    jMenuHelpContents.add(jMenuItemCredits);

    jMenuItemAbout.setText("About");
    jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemAboutActionPerformed(evt);
        }
    });
    jMenuHelpContents.add(jMenuItemAbout);

    jMenuBar.add(jMenuHelpContents);

    setJMenuBar(jMenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jSplitPaneExternal, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSplitPaneExternal, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
      execute(APP_EXIT);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewProjectActionPerformed
      execute(PROJ_NEW);
    }//GEN-LAST:event_jMenuItemNewProjectActionPerformed

    private void jMenuItemOpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenProjectActionPerformed
     execute(PROJ_OPEN);
    }//GEN-LAST:event_jMenuItemOpenProjectActionPerformed

    private void jMenuItemCloseProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseProjectActionPerformed
      execute(PROJ_CLOSE);
    }//GEN-LAST:event_jMenuItemCloseProjectActionPerformed

    private void jMenuItemSaveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveProjectActionPerformed
      execute(PROJ_SAVE);
    }//GEN-LAST:event_jMenuItemSaveProjectActionPerformed

    private void jMenuItemSaveAsProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsProjectActionPerformed
      execute(PROJ_SAVEAS);
    }//GEN-LAST:event_jMenuItemSaveAsProjectActionPerformed

    private void jButtonNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewProjectActionPerformed
      execute(PROJ_NEW);
    }//GEN-LAST:event_jButtonNewProjectActionPerformed

    private void jButtonOpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenProjectActionPerformed
      execute(PROJ_OPEN);
    }//GEN-LAST:event_jButtonOpenProjectActionPerformed

    private void jButtonSaveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveProjectActionPerformed
      execute(PROJ_SAVE);
    }//GEN-LAST:event_jButtonSaveProjectActionPerformed

    private void jButtonSaveProjectAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveProjectAsActionPerformed
      execute(PROJ_SAVEAS);
    }//GEN-LAST:event_jButtonSaveProjectAsActionPerformed

    private void jButtonConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigureActionPerformed
      execute(OPTION_CONFIGURE);
    }//GEN-LAST:event_jButtonConfigureActionPerformed

    private void jMenuItemConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigureActionPerformed
      execute(OPTION_CONFIGURE);
    }//GEN-LAST:event_jMenuItemConfigureActionPerformed

    private void jButtonDisassembleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisassembleActionPerformed
      execute(SOURCE_DISASS);
    }//GEN-LAST:event_jButtonDisassembleActionPerformed

    private void jMenuItemDissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDissActionPerformed
      execute(SOURCE_DISASS);
    }//GEN-LAST:event_jMenuItemDissActionPerformed

    private void jMenuItemViewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewProjectActionPerformed
      execute(OPTION_VIEWPRJ); 
    }//GEN-LAST:event_jMenuItemViewProjectActionPerformed

    private void jMenuItemDissSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDissSaveAsActionPerformed
      execute(SOURCE_EXPASDIS); 
    }//GEN-LAST:event_jMenuItemDissSaveAsActionPerformed

    private void jButtonExportAsDissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportAsDissActionPerformed
      execute(SOURCE_EXPASDIS); 
    }//GEN-LAST:event_jButtonExportAsDissActionPerformed

    private void jButtonExportAsSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportAsSourceActionPerformed
      execute(SOURCE_EXPASSOURCE); 
    }//GEN-LAST:event_jButtonExportAsSourceActionPerformed

    private void jMenuItemSourceSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSourceSaveAsActionPerformed
      execute(SOURCE_EXPASSOURCE);
    }//GEN-LAST:event_jMenuItemSourceSaveAsActionPerformed

    private void jButtonViewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewProjectActionPerformed
      execute(OPTION_VIEWPRJ); 
    }//GEN-LAST:event_jButtonViewProjectActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
      execute(APP_EXIT); 
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jMenuItemClearDMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearDMemActionPerformed
      execute(MEM_CLEARDCOM);
    }//GEN-LAST:event_jMenuItemClearDMemActionPerformed

    private void jButtonClearDMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearDMemActionPerformed
      execute(MEM_CLEARDCOM);
    }//GEN-LAST:event_jButtonClearDMemActionPerformed

    private void jButtonClearUMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearUMemActionPerformed
      execute(MEM_CLEARUCOM);
    }//GEN-LAST:event_jButtonClearUMemActionPerformed

    private void jMenuItemClearUMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearUMemActionPerformed
      execute(MEM_CLEARUCOM);
    }//GEN-LAST:event_jMenuItemClearUMemActionPerformed

    private void jButtonMarkCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarkCodeActionPerformed
      execute(MEM_MARKCODE);
    }//GEN-LAST:event_jButtonMarkCodeActionPerformed

    private void jButtonMarkDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarkDataActionPerformed
      execute(MEM_MARKDATA);
    }//GEN-LAST:event_jButtonMarkDataActionPerformed

    private void jMenuItemMarkCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarkCodeActionPerformed
      execute(MEM_MARKCODE);
    }//GEN-LAST:event_jMenuItemMarkCodeActionPerformed

    private void jMenuItemMarkDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarkDataActionPerformed
      execute(MEM_MARKDATA);  
    }//GEN-LAST:event_jMenuItemMarkDataActionPerformed

    private void jButtonSIDLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIDLDActionPerformed
      execute(OPTION_SIDLD);
    }//GEN-LAST:event_jButtonSIDLDActionPerformed

    private void jMenuItemSIDLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSIDLDActionPerformed
      execute(OPTION_SIDLD);
    }//GEN-LAST:event_jMenuItemSIDLDActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
      execute(PROJ_CLOSE);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jMenuItemContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContentsActionPerformed
      execute(HELP_CONTENTS);
    }//GEN-LAST:event_jMenuItemContentsActionPerformed

    private void jMenuItemLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLicenseActionPerformed
      execute(HELP_LICENSE);
    }//GEN-LAST:event_jMenuItemLicenseActionPerformed

    private void jMenuItemCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreditsActionPerformed
      execute(HELP_CREDITS);
    }//GEN-LAST:event_jMenuItemCreditsActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
      execute(HELP_ABOUT);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void rSyntaxTextAreaDisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSyntaxTextAreaDisMouseClicked
      try {
        // get starting position of clicked point  
        int pos=Utilities.getRowStart(rSyntaxTextAreaDis, rSyntaxTextAreaDis.getCaretPosition());
        
        // address of this instruction
        int addr=Integer.decode("0x"+rSyntaxTextAreaDis.getDocument().getText(pos,4));
                
        //scroll to that point
        jTableMemory.scrollRectToVisible(jTableMemory.getCellRect(addr,0, true)); 
        
        // select this row
        jTableMemory.setRowSelectionInterval(addr, addr);
      } catch (Exception e) {
          System.err.println(e);
      }
    }//GEN-LAST:event_rSyntaxTextAreaDisMouseClicked

    private void jMenuItemFindDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFindDisActionPerformed
      execute(SOURCE_FINDD);
    }//GEN-LAST:event_jMenuItemFindDisActionPerformed

    private void jMenuItemFindSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFindSourceActionPerformed
      execute(SOURCE_FINDS);
    }//GEN-LAST:event_jMenuItemFindSourceActionPerformed

    private void jButtonFindDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindDisActionPerformed
      execute(SOURCE_FINDD);
    }//GEN-LAST:event_jButtonFindDisActionPerformed

    private void jButtonFindSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindSourceActionPerformed
      execute(SOURCE_FINDS);
    }//GEN-LAST:event_jButtonFindSourceActionPerformed

    private void jButtonClearUMem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearUMem1ActionPerformed
      execute(MEM_ADDCOMM);
    }//GEN-LAST:event_jButtonClearUMem1ActionPerformed

    private void jMenuItemAddCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCommentActionPerformed
      execute(MEM_ADDCOMM);
    }//GEN-LAST:event_jMenuItemAddCommentActionPerformed

    private void jButtonClearUMem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearUMem2ActionPerformed
      execute(MEM_ADDLABEL);
    }//GEN-LAST:event_jButtonClearUMem2ActionPerformed

    private void jMenuItemUserLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserLabelActionPerformed
      execute(MEM_ADDLABEL);
    }//GEN-LAST:event_jMenuItemUserLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDisassemblerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDisassemblerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDisassemblerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDisassemblerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDisassemblerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearDMem;
    private javax.swing.JButton jButtonClearUMem;
    private javax.swing.JButton jButtonClearUMem1;
    private javax.swing.JButton jButtonClearUMem2;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonConfigure;
    private javax.swing.JButton jButtonDisassemble;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExportAsDiss;
    private javax.swing.JButton jButtonExportAsSource;
    private javax.swing.JButton jButtonFindDis;
    private javax.swing.JButton jButtonFindSource;
    private javax.swing.JButton jButtonMarkCode;
    private javax.swing.JButton jButtonMarkData;
    private javax.swing.JButton jButtonNewProject;
    private javax.swing.JButton jButtonOpenProject;
    private javax.swing.JButton jButtonSIDLD;
    private javax.swing.JButton jButtonSaveProject;
    private javax.swing.JButton jButtonSaveProjectAs;
    private javax.swing.JButton jButtonViewProject;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelpContents;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemAddComment;
    private javax.swing.JMenuItem jMenuItemClearDMem;
    private javax.swing.JMenuItem jMenuItemClearUMem;
    private javax.swing.JMenuItem jMenuItemCloseProject;
    private javax.swing.JMenuItem jMenuItemConfigure;
    private javax.swing.JMenuItem jMenuItemContents;
    private javax.swing.JMenuItem jMenuItemCredits;
    private javax.swing.JMenuItem jMenuItemDiss;
    private javax.swing.JMenuItem jMenuItemDissSaveAs;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemFindDis;
    private javax.swing.JMenuItem jMenuItemFindSource;
    private javax.swing.JMenuItem jMenuItemLicense;
    private javax.swing.JMenuItem jMenuItemMarkCode;
    private javax.swing.JMenuItem jMenuItemMarkData;
    private javax.swing.JMenuItem jMenuItemNewProject;
    private javax.swing.JMenuItem jMenuItemOpenProject;
    private javax.swing.JMenuItem jMenuItemSIDLD;
    private javax.swing.JMenuItem jMenuItemSaveAsProject;
    private javax.swing.JMenuItem jMenuItemSaveProject;
    private javax.swing.JMenuItem jMenuItemSourceSaveAs;
    private javax.swing.JMenuItem jMenuItemUserLabel;
    private javax.swing.JMenuItem jMenuItemViewProject;
    private javax.swing.JMenu jMenuMarkCode;
    private javax.swing.JMenu jMenuOption;
    private javax.swing.JMenu jMenuSource;
    private javax.swing.JScrollPane jScrollPaneLeft;
    private javax.swing.JScrollPane jScrollPaneMemory;
    private javax.swing.JScrollPane jScrollPaneRight;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparatorButton1;
    private javax.swing.JToolBar.Separator jSeparatorButton2;
    private javax.swing.JToolBar.Separator jSeparatorButton3;
    private javax.swing.JPopupMenu.Separator jSeparatorHelp1;
    private javax.swing.JPopupMenu.Separator jSeparatorOption;
    private javax.swing.JPopupMenu.Separator jSeparatorProject1;
    private javax.swing.JPopupMenu.Separator jSeparatorProject2;
    private javax.swing.JPopupMenu.Separator jSeparatorProject3;
    private javax.swing.JSplitPane jSplitPaneExternal;
    private javax.swing.JSplitPane jSplitPaneInternal;
    private javax.swing.JTable jTableMemory;
    private javax.swing.JToolBar jToolBar;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea rSyntaxTextAreaDis;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea rSyntaxTextAreaSource;
    // End of variables declaration//GEN-END:variables

  @Override
  public void execute(int type) {
    switch (type) {
      case PROJ_NEW:
        projectNew();
        break;
      case PROJ_CLOSE:  
        projectClose(); 
        break;  
      case PROJ_OPEN:
        projectOpen();
        break;
      case PROJ_SAVE:
        projectSave(); 
        break;        
      case PROJ_SAVEAS:
        projectSaveAs();
        break;        
      case OPTION_CONFIGURE:
        jOptionDialog.setVisible(true);
        break;
      case OPTION_VIEWPRJ:
        projectView();
        break;   
      case OPTION_SIDLD:
        optionSIDLD();  
        break;        
      case SOURCE_DISASS:
        disassembly();
        break;            
      case SOURCE_EXPASDIS:
        exportAs(rSyntaxTextAreaDis.getText());  
        break;        
      case SOURCE_EXPASSOURCE:
        exportAs(rSyntaxTextAreaSource.getText());    
        break;
      case SOURCE_FINDD:
        findDialogDis.setVisible(true);
        break;
      case SOURCE_FINDS:
        findDialogSource.setVisible(true);
        break;
      case APP_EXIT:
        exit();
        break;        
      case MEM_CLEARDCOM:
        clearDasmComment();
        break;
       case MEM_CLEARUCOM:
        clearUserComment();
        break;    
       case MEM_ADDCOMM:
         addComment();
         break;
       case MEM_ADDLABEL:
         addLabel();
         break;         
       case MEM_MARKCODE:
         markAsCode();  
         break;
       case MEM_MARKDATA:
         markAsData();  
         break;
         
       case HELP_CONTENTS: 
         jHelpFrame.setVisible(true);
         break;
       case HELP_LICENSE:
         jLicenseDialog.setVisible(true);  
         break;
       case HELP_CREDITS:
         jCreditsDialog.setVisible(true);
         break;  
       case HELP_ABOUT:
         jAboutDialog.setVisible(true);
         break;
    }
        
  }
  
  /**
   * Project new user action
   */
  private void projectNew() {
    if (project != null && !project.equals(savedProject)) {
      JOptionPane.showMessageDialog(this, "Project not saved. Close it, then create a new one.", "Information", JOptionPane.WARNING_MESSAGE);
    } else {
        project=new Project();
        savedProject=project.clone();
        projectFile=null;
        jProjectDialog.setUp(project);            
        jProjectDialog.setVisible(true);
        dataTableModelMemory.setData(project.memory);
        dataTableModelMemory.fireTableDataChanged();
        execute(SOURCE_DISASS);
      }    
  }
  
  /**
   * Project close user action
   */
  private void projectClose() {
    if (project != null && !project.equals(savedProject)) {
      int res=JOptionPane.showConfirmDialog(this, "Project not saved. Close it anywere?", "Information", JOptionPane.YES_NO_OPTION);
      if (res==JOptionPane.YES_OPTION) {
        project=null;
        savedProject=null;
        projectFile=null;
        rSyntaxTextAreaSource.setText("");
        rSyntaxTextAreaDis.setText("");
        dataTableModelMemory.setData(null);
        dataTableModelMemory.fireTableDataChanged();
      }
    }       
  }
  
  /**
   * Project open user action
   */
  private void projectOpen() {
    if (project != null && !project.equals(savedProject)) {
      JOptionPane.showMessageDialog(this, "Project not saved. Close it, then create a new one.", "Information", JOptionPane.WARNING_MESSAGE);
    } else {
        int retVal=projectChooserFile.showOpenDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
          projectFile=projectChooserFile.getSelectedFile();
          project=new Project();
          if (!FileManager.instance.readProjectFile(projectFile , project)) {
              JOptionPane.showMessageDialog(this, "Error reading project file", "Error", JOptionPane.ERROR_MESSAGE);
          } else {
              JOptionPane.showMessageDialog(this, "File readed", "Information", JOptionPane.INFORMATION_MESSAGE);
              execute(SOURCE_DISASS);
            }
            dataTableModelMemory.setData(project.memory);
            dataTableModelMemory.fireTableDataChanged();
          }
       }         
  }
  
  /**
   * Project save user action
   */
  private void projectSave() {
    if (project==null) {
      JOptionPane.showMessageDialog(this, "There is nothing to save", "Information", JOptionPane.INFORMATION_MESSAGE);  
    } else {
        if (projectFile==null) execute (PROJ_SAVEAS);
        else {
          if (!FileManager.instance.writeProjectFile(projectFile , project)) {
            JOptionPane.showMessageDialog(this, "Error writing project file", "Error", JOptionPane.ERROR_MESSAGE);
          } else {
              JOptionPane.showMessageDialog(this, "File saved", "Information", JOptionPane.INFORMATION_MESSAGE);
            }  
        }
      }      
  } 
  
  /**
   * Project save as user action
   */
  private void projectSaveAs() {
    if (project==null) {
      JOptionPane.showMessageDialog(this, "There is nothing to save", "Information", JOptionPane.INFORMATION_MESSAGE);  
    } else {
        int retVal=projectChooserFile.showSaveDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
          projectFile=projectChooserFile.getSelectedFile();
          if (!FileManager.instance.writeProjectFile(projectFile , project)) {
            JOptionPane.showMessageDialog(this, "Error writing project file", "Error", JOptionPane.ERROR_MESSAGE);
          } else {
              JOptionPane.showMessageDialog(this, "File saved", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
     }      
  }
  
  /**
   * Project view user action
   */
  private void projectView() {
    if (project==null) {
      JOptionPane.showMessageDialog(this, "No project are actually being used.", "Warning", JOptionPane.WARNING_MESSAGE);   
    }  else {
         jProjectDialog.setUp(project);
         jProjectDialog.setVisible(true);
         execute(SOURCE_DISASS);
        }      
  }

  /**
   * Export as of the select text
   * 
   * @param text the text to export
   */
  private void exportAs(String text) {
     File file; 
      
     if (text==null || "".equals(text)) {
          JOptionPane.showMessageDialog(this, "There is nothing to save", "Information", JOptionPane.INFORMATION_MESSAGE);  
        } else {
            int retVal=exportAsChooserFile.showSaveDialog(this);
            if (retVal == JFileChooser.APPROVE_OPTION) {
              file=projectChooserFile.getSelectedFile();
              if (!FileManager.instance.writeTxtFile(file , text)) {
                JOptionPane.showMessageDialog(this, "Error writing txt file", "Error", JOptionPane.ERROR_MESSAGE);
              } else {
                  JOptionPane.showMessageDialog(this, "File saved", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            }
          }   
  }
 
  /**
   * Exit from program
   */
  private void exit() {
    if (project != null && !project.equals(savedProject)) {
      int res=JOptionPane.showConfirmDialog(this, "Project not saved. Exit anywere?", "Information", JOptionPane.YES_NO_OPTION);
      if (res==JOptionPane.YES_OPTION) {      
        System.exit(0);
      }
    } else System.exit(0);
  }
  
  /**
   * Clear the dasm label by adding a user null label
   */
  private void clearDasmComment() {
    MemoryDasm mem;   
      
    int rows[]=jTableMemory.getSelectedRows();
        
    for (int i=0; i<rows.length; i++) {
      mem= project.memory[rows[i]];
      if (mem.dasmComment!=null) mem.userComment="";
    }
    
    dataTableModelMemory.fireTableDataChanged();
  }
  
  /**
   * Clear the dasm label by adding a user null label
   */
  private void clearUserComment() {
    MemoryDasm mem;   
      
    int rows[]=jTableMemory.getSelectedRows();
        
    for (int i=0; i<rows.length; i++) {
      mem= project.memory[rows[i]];
      if (mem.userComment!=null) mem.userComment=null;
    }
    
    dataTableModelMemory.fireTableDataChanged();
  } 
  
  /**
   * Mark user selection as code
   */
  private void markAsCode() {
    MemoryDasm mem;   
      
    int rows[]=jTableMemory.getSelectedRows();
        
    for (int i=0; i<rows.length; i++) {
      mem= project.memory[rows[i]];
      mem.isCode=true;
      mem.isData=false;
    }
    
    dataTableModelMemory.fireTableDataChanged();  
  }
  
  /**
   * Mark user selection as code
   */
  private void markAsData() {
    MemoryDasm mem;   
      
    int rows[]=jTableMemory.getSelectedRows();
        
    for (int i=0; i<rows.length; i++) {
      mem= project.memory[rows[i]];
      mem.isData=true;
      mem.isCode=false;
      if (option.eraseDComm) mem.dasmComment=null;
    }
    
    dataTableModelMemory.fireTableDataChanged();  
  }

  /**
   * Apply SIDLD flags to memory
   */
  private void optionSIDLD() {
    if (project==null) {
      JOptionPane.showMessageDialog(this, "No project are actually being used.", "Warning", JOptionPane.WARNING_MESSAGE);   
    }  else {  
         int res=JOptionPane.showConfirmDialog(this, "Confirm to apply SIDLD memory flags to code/data inm table?", "Information", JOptionPane.YES_NO_OPTION);
         if (res == JFileChooser.APPROVE_OPTION) {
             
           for (int i=0; i<project.memoryFlags.length; i++) {        
               project.memory[i].isData = (project.memoryFlags[i] & 
                       (memoryState.MEM_READ | memoryState.MEM_READ_FIRST |
                       memoryState.MEM_WRITE | memoryState.MEM_WRITE_FIRST |
                       memoryState.MEM_SAMPLE)) !=0;
      
               project.memory[i].isCode = (project.memoryFlags[i] & 
                       (memoryState.MEM_EXECUTE | memoryState.MEM_EXECUTE_FIRST)) !=0;                                             
           }
         }
         
         JOptionPane.showMessageDialog(this, "Operation done.", "Info", JOptionPane.INFORMATION_MESSAGE);  
       }  
  }
  
  /**
   * Disassembly the memory
   */
  private void disassembly() {
    disassembly.dissassembly(project.fileType, project.inB, option, project.memory, false);
    disassembly.dissassembly(project.fileType, project.inB, option, project.memory, true);
    int lineS=0;
    int lineD=0;
    try {
      lineS=rSyntaxTextAreaSource.getLineOfOffset(rSyntaxTextAreaSource.getCaretPosition());        
      lineD=rSyntaxTextAreaDis.getLineOfOffset(rSyntaxTextAreaDis.getCaretPosition());        
    } catch (BadLocationException ex) {
        System.err.println(ex);
    }
    rSyntaxTextAreaSource.setText(disassembly.source);    
    try {
      rSyntaxTextAreaSource.setCaretPosition(rSyntaxTextAreaSource.getDocument()
                        .getDefaultRootElement().getElement(lineS)
                        .getStartOffset());
      rSyntaxTextAreaSource.requestFocusInWindow();
    } catch (Exception ex) {
        System.err.println(ex);
    }
    
    rSyntaxTextAreaDis.setText(disassembly.disassembly);
    try {
      rSyntaxTextAreaDis.setCaretPosition(rSyntaxTextAreaDis.getDocument()
                        .getDefaultRootElement().getElement(lineD)
                        .getStartOffset());
      rSyntaxTextAreaDis.requestFocusInWindow();
    } catch (Exception ex) {
        System.err.println(ex);
    }       
    
    memoryTableCellRenderer.setDisassembly(disassembly);      
  }

  /**
   * Add a user label to the selected memory address
   */
  private void addComment() {
    int row=jTableMemory.getSelectedRow();
    if (row<0) {
      JOptionPane.showMessageDialog(this, "No row selected", "Warning", JOptionPane.WARNING_MESSAGE);  
      return;
    }
      
    MemoryDasm mem= project.memory[row];
    String comment=JOptionPane.showInputDialog(this, "Insert the comment for the selected memory location", mem.userComment);
    if (comment!=null) mem.userComment=comment;  
    dataTableModelMemory.fireTableDataChanged(); 
  }

  /**
   * Add a user label to the selected memory address
   */
  private void addLabel() {
    int row=jTableMemory.getSelectedRow();
    if (row<0) {
      JOptionPane.showMessageDialog(this, "No row selected", "Warning", JOptionPane.WARNING_MESSAGE);  
      return;
    }
    
    MemoryDasm mem= project.memory[row];
    String initial="";
    if (mem.userLocation!=null) initial=mem.userLocation;
    else if (mem.dasmLocation!=null && !"".equals(mem.dasmLocation)) initial=mem.dasmLocation;
    
    String label=JOptionPane.showInputDialog(this, "Insert the label for the selected memory location", initial);  
    if (label!=null) {
      if ("".equals(label)) {
        JOptionPane.showMessageDialog(this, "User label erased", "Information", JOptionPane.INFORMATION_MESSAGE);   
        mem.userLocation=null;
        return;
      }  
      
      if (label.contains(" ")) {
        JOptionPane.showMessageDialog(this, "Label must not contain spaces", "Error", JOptionPane.ERROR_MESSAGE);   
        return;
      }
      
      // see if the label is already defined
      for (MemoryDasm memory : project.memory) {
        if (label.equals(memory.dasmLocation) || label.equals(memory.userLocation)) {
          JOptionPane.showMessageDialog(this, "This label is already used into the source", "Error", JOptionPane.ERROR_MESSAGE);  
          return;
       }
      }
      
      mem.userLocation=label;
      dataTableModelMemory.fireTableDataChanged(); 
    }
  }
  
}
