/**
 * @(#)JGlassPanel 2022/05/03
 *
 * ICE Team free software group
 *
 * This file is part of C64 Java Software Emulator.
 * See README for copyright notice.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 *  02111-1307  USA.
 */
package sw_emulator.swing;

import sw_emulator.software.Assembler;
import sw_emulator.swing.main.Option;

/**
 * A panel for 64Tass assembler option 
 * 
 * @author ice
 */
public class JGlassPanel extends javax.swing.JPanel {
    /** Option file to use */
    Option option;
    
    /**
     * Creates new form JGlassPanel
     */
    public JGlassPanel() {
        initComponents();
    }

    
    /**
     * Set up the panel with the option 
     * 
     * @param option the option to use
     */
    public void setUp(Option option) {
      this.option=option;
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGlassStarting = new javax.swing.ButtonGroup();
        buttonGroupGlassLabel = new javax.swing.ButtonGroup();
        buttonGroupGlassOrigin = new javax.swing.ButtonGroup();
        buttonGroupGlassByte = new javax.swing.ButtonGroup();
        buttonGroupGlassWord = new javax.swing.ButtonGroup();
        buttonGroupGlassComment = new javax.swing.ButtonGroup();
        buttonGroupGlassBlockComment = new javax.swing.ButtonGroup();
        buttonGroupGlassWordSwapped = new javax.swing.ButtonGroup();
        buttonGroupGlassTribyte = new javax.swing.ButtonGroup();
        buttonGroupGlassLong = new javax.swing.ButtonGroup();
        buttonGroupGlassAddress = new javax.swing.ButtonGroup();
        buttonGroupGlassStackWord = new javax.swing.ButtonGroup();
        buttonGroupGlassMonoSprite = new javax.swing.ButtonGroup();
        buttonGroupGlassMultiSprite = new javax.swing.ButtonGroup();
        buttonGroupGlassText = new javax.swing.ButtonGroup();
        buttonGroupGlassNumText = new javax.swing.ButtonGroup();
        buttonGroupGlassZeroText = new javax.swing.ButtonGroup();
        buttonGroupGlassHighText = new javax.swing.ButtonGroup();
        buttonGroupGlassShiftText = new javax.swing.ButtonGroup();
        buttonGroupGlassScreenText = new javax.swing.ButtonGroup();
        buttonGroupGlassPetsciiText = new javax.swing.ButtonGroup();
        jLabelGlassLabelDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassLabelName = new javax.swing.JRadioButton();
        jScrollPaneGlassByte = new javax.swing.JScrollPane();
        jTextPaneGlassLabelName = new javax.swing.JTextPane();
        jLabelGlassByteDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassDbByte = new javax.swing.JRadioButton();
        jScrollPaneGlassWord = new javax.swing.JScrollPane();
        jTextPaneGlassDbByte = new javax.swing.JTextPane();
        jLabelGlassWordDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassDwWord = new javax.swing.JRadioButton();
        jScrollPaneGlassDotWord = new javax.swing.JScrollPane();
        jTextPaneGlassDwWord = new javax.swing.JTextPane();
        jLabelGlassCommentDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassSemicolonComment = new javax.swing.JRadioButton();
        jScrollPaneTmpxSemicolonComment1 = new javax.swing.JScrollPane();
        jTextPaneGlassSemicolonComment = new javax.swing.JTextPane();
        jLabelTmpxBlockCommentDeclaration1 = new javax.swing.JLabel();
        jRadioButtonTmpxSemicolonBlockComment1 = new javax.swing.JRadioButton();
        jScrollPaneTmpxSemicolonBlockComment1 = new javax.swing.JScrollPane();
        jTextPaneTmpxSemicolonBlockComment1 = new javax.swing.JTextPane();
        jLabelGlassOriginDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassOrigin = new javax.swing.JRadioButton();
        jScrollPaneTmpxAsterixOrigin1 = new javax.swing.JScrollPane();
        jTextPaneGlassOrigin = new javax.swing.JTextPane();
        jLabelGlassStartingDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassFakeStarting = new javax.swing.JRadioButton();
        jScrollPaneGlassFakeStarting = new javax.swing.JScrollPane();
        jTextPaneGlassFakeStarting = new javax.swing.JTextPane();
        jLabelGlassMonoSpriteDeclaration = new javax.swing.JLabel();
        jLabelGlassMultiSpriteDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassByteHexMonoSprite = new javax.swing.JRadioButton();
        jRadioButtonGlassByteHexMultiSprite = new javax.swing.JRadioButton();
        jScrollPaneTmpxByteHexMultiSprite1 = new javax.swing.JScrollPane();
        TmpxPaneGlassByteHexMultiSprite = new javax.swing.JTextPane();
        jScrollPaneTmpxByteHexMonoSprite1 = new javax.swing.JScrollPane();
        jTextPaneGlassByteHexMonoSprite = new javax.swing.JTextPane();
        jRadioButtonGlassByteBinMonoSprite = new javax.swing.JRadioButton();
        jRadioButtonGlassByteBinMultiSprite = new javax.swing.JRadioButton();
        jScrollPaneTmpxByteBinMultiSprite1 = new javax.swing.JScrollPane();
        jTextPaneGlassByteBinMultiSprite = new javax.swing.JTextPane();
        jScrollPaneTmpxByteBinMonoSprite1 = new javax.swing.JScrollPane();
        jTextPaneGlassByteBinMonoSprite = new javax.swing.JTextPane();
        jRadioButtonGlassMacroHexMonoSprite = new javax.swing.JRadioButton();
        jRadioButtonGlassMacroHexMultiSprite = new javax.swing.JRadioButton();
        jScrollPaneTmpxMacroHexMultiSprite1 = new javax.swing.JScrollPane();
        jTextPaneGlassMacroHexMultiSprite = new javax.swing.JTextPane();
        jScrollPaneTmpxMacroHexMonoSprite1 = new javax.swing.JScrollPane();
        jTextPaneGlassMacroHexMonoSprite = new javax.swing.JTextPane();
        jRadioButtonGlassMacroBinMonoSprite = new javax.swing.JRadioButton();
        jRadioButtonGlassMacroBinMultiSprite = new javax.swing.JRadioButton();
        jScrollPaneTmpxMacroBinMultiSprite1 = new javax.swing.JScrollPane();
        jTextPaneGlassMacroBinMultiSprite = new javax.swing.JTextPane();
        jScrollPaneTmpxMacroBinMonoSprite1 = new javax.swing.JScrollPane();
        jTextPaneGlassMacroBinMonoSprite = new javax.swing.JTextPane();
        jLabelGlassTribyteDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassMacroTribyte = new javax.swing.JRadioButton();
        jScrollPaneTmpxMacroTribyte1 = new javax.swing.JScrollPane();
        jTextPaneGlassMacroTribyte = new javax.swing.JTextPane();
        jLabelGlassLongDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassDdLong = new javax.swing.JRadioButton();
        jScrollPaneTmpxMacroLong1 = new javax.swing.JScrollPane();
        jTextPaneGlassMacroLong = new javax.swing.JTextPane();
        jLabelGlassWordSwappedDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassMacroWordSwapped = new javax.swing.JRadioButton();
        jScrollPaneTmpxMacroWordSwapped1 = new javax.swing.JScrollPane();
        jTextPaneGlassMacroWordSwapped = new javax.swing.JTextPane();
        jLabelGlassTextDeclaration = new javax.swing.JLabel();
        jRadioButtonTmpxDotText1 = new javax.swing.JRadioButton();
        jScrollPaneTmpxDotText1 = new javax.swing.JScrollPane();
        jTextPaneTmpxDotText1 = new javax.swing.JTextPane();
        jLabelGlassNumTextDeclaration = new javax.swing.JLabel();
        jRadioButtonTmpxPTextNumText1 = new javax.swing.JRadioButton();
        jScrollPaneTmpxDotTextNumText1 = new javax.swing.JScrollPane();
        jTextPaneTmpxDotTextNumText1 = new javax.swing.JTextPane();
        jLabelGlassZeroTextDeclaration = new javax.swing.JLabel();
        jRadioButtonTmpxDotNullZeroText1 = new javax.swing.JRadioButton();
        jScrollPaneTmpxDotNullZeroText1 = new javax.swing.JScrollPane();
        jTextPaneTmpxDotNullZeroText1 = new javax.swing.JTextPane();
        jLabelGlassAddressDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassDwAddress = new javax.swing.JRadioButton();
        jScrollPaneTmpxDotAddrAddress1 = new javax.swing.JScrollPane();
        jTextPaneGlassDwAddress = new javax.swing.JTextPane();
        jLabelTmpxGlassStackWordDeclaration = new javax.swing.JLabel();
        jRadioButtonGlassMacroStackWord = new javax.swing.JRadioButton();
        jScrollPaneTmpxDotRtaStackWord1 = new javax.swing.JScrollPane();
        jTextPaneGlassMacroStackWord = new javax.swing.JTextPane();
        jLabelGlassHighTextDeclaration = new javax.swing.JLabel();
        jRadioButtonTmpxDotShiftHighText1 = new javax.swing.JRadioButton();
        jScrollPaneTmpxDotShiftHighText1 = new javax.swing.JScrollPane();
        jTextPaneTmpxDotShiftHighText1 = new javax.swing.JTextPane();
        jLabelGlassShiftTextDeclaration = new javax.swing.JLabel();
        jRadioButtonTmpxDotShiflShiftText1 = new javax.swing.JRadioButton();
        jScrollPaneTmpxDotShiftlShiftText1 = new javax.swing.JScrollPane();
        jTextPaneTmpxDotShiflShiftText1 = new javax.swing.JTextPane();
        jLabelGlassScreenTextDeclaration = new javax.swing.JLabel();
        jRadioButtonTmpxDotScreenText1 = new javax.swing.JRadioButton();
        jScrollPaneTmpxDotScreenText1 = new javax.swing.JScrollPane();
        jTextPaneTmpxDotScreenText1 = new javax.swing.JTextPane();
        jLabelGlassPetasciiTextDeclaration = new javax.swing.JLabel();
        jRadioButtonTmpxDotPetasciiText1 = new javax.swing.JRadioButton();
        jScrollPaneTmpxDotPetasciiText1 = new javax.swing.JScrollPane();
        jTextPaneTmpxDotPetasciiText1 = new javax.swing.JTextPane();
        jRadioButtonGlassLabelNameColon = new javax.swing.JRadioButton();
        jScrollPaneDasmLabelNameColon = new javax.swing.JScrollPane();
        jTextPaneGlassLabelNameColon = new javax.swing.JTextPane();

        jLabelGlassLabelDeclaration.setText("Label:");

        buttonGroupGlassLabel.add(jRadioButtonGlassLabelName);
        jRadioButtonGlassLabelName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassLabelNameItemStateChanged(evt);
            }
        });

        jScrollPaneGlassByte.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneGlassByte.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassLabelName.setEditable(false);
        jTextPaneGlassLabelName.setContentType("text/html"); // NOI18N
        jTextPaneGlassLabelName.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <font color='black'>zzzz</font>\n    </p\n  </body>\n</html>\n");
        jScrollPaneGlassByte.setViewportView(jTextPaneGlassLabelName);

        jLabelGlassByteDeclaration.setText("Byte:");

        buttonGroupGlassByte.add(jRadioButtonGlassDbByte);
        jRadioButtonGlassDbByte.setSelected(true);
        jRadioButtonGlassDbByte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassDbByteItemStateChanged(evt);
            }
        });

        jScrollPaneGlassWord.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneGlassWord.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassDbByte.setEditable(false);
        jTextPaneGlassDbByte.setContentType("text/html"); // NOI18N
        jTextPaneGlassDbByte.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>$xx</font><br>\n     <b> db</b> <font color='blue'>dd</font><br>\n     <b> db</b> <font color='green'>%bb</font><br>\n     <b> db</b> <font color='purple'>'c'</font>\n    </p>\n  </body>\n</html>\n");
        jScrollPaneGlassWord.setViewportView(jTextPaneGlassDbByte);

        jLabelGlassWordDeclaration.setText("Word:");

        jRadioButtonGlassDwWord.setSelected(true);
        jRadioButtonGlassDwWord.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassDwWordItemStateChanged(evt);
            }
        });

        jScrollPaneGlassDotWord.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneGlassDotWord.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassDwWord.setEditable(false);
        jTextPaneGlassDwWord.setContentType("text/html"); // NOI18N
        jTextPaneGlassDwWord.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> dw</b> <font color='red'>$xxyy</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneGlassDotWord.setViewportView(jTextPaneGlassDwWord);

        jLabelGlassCommentDeclaration.setText("Comment:");

        buttonGroupGlassComment.add(jRadioButtonGlassSemicolonComment);
        jRadioButtonGlassSemicolonComment.setSelected(true);
        jRadioButtonGlassSemicolonComment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassSemicolonCommentItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxSemicolonComment1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxSemicolonComment1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassSemicolonComment.setEditable(false);
        jTextPaneGlassSemicolonComment.setContentType("text/html"); // NOI18N
        jTextPaneGlassSemicolonComment.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <b>;</b> xxx\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxSemicolonComment1.setViewportView(jTextPaneGlassSemicolonComment);

        jLabelTmpxBlockCommentDeclaration1.setText("Block Comment:");

        buttonGroupGlassBlockComment.add(jRadioButtonTmpxSemicolonBlockComment1);
        jRadioButtonTmpxSemicolonBlockComment1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTmpxSemicolonBlockComment1ItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxSemicolonBlockComment1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxSemicolonBlockComment1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneTmpxSemicolonBlockComment1.setEditable(false);
        jTextPaneTmpxSemicolonBlockComment1.setContentType("text/html"); // NOI18N
        jTextPaneTmpxSemicolonBlockComment1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <b>;</b> xxx\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxSemicolonBlockComment1.setViewportView(jTextPaneTmpxSemicolonBlockComment1);

        jLabelGlassOriginDeclaration.setText("Origin:");

        buttonGroupGlassOrigin.add(jRadioButtonGlassOrigin);
        jRadioButtonGlassOrigin.setSelected(true);
        jRadioButtonGlassOrigin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassOriginItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxAsterixOrigin1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxAsterixOrigin1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassOrigin.setEditable(false);
        jTextPaneGlassOrigin.setContentType("text/html"); // NOI18N
        jTextPaneGlassOrigin.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <b>org</b> $xxyy\n    </p>\n  </body>\n</html>\n\n");
        jScrollPaneTmpxAsterixOrigin1.setViewportView(jTextPaneGlassOrigin);

        jLabelGlassStartingDeclaration.setText("Starting:");

        buttonGroupGlassStarting.add(jRadioButtonGlassFakeStarting);
        jRadioButtonGlassFakeStarting.setSelected(true);
        jRadioButtonGlassFakeStarting.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassFakeStartingItemStateChanged(evt);
            }
        });

        jScrollPaneGlassFakeStarting.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneGlassFakeStarting.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassFakeStarting.setEditable(false);
        jTextPaneGlassFakeStarting.setContentType("text/html"); // NOI18N
        jTextPaneGlassFakeStarting.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <b>cpu</b>  equ 80\n    </p>\n  </body>\n</html>\n");
        jScrollPaneGlassFakeStarting.setViewportView(jTextPaneGlassFakeStarting);

        jLabelGlassMonoSpriteDeclaration.setText("Monocolor sprite:");

        jLabelGlassMultiSpriteDeclaration.setText("Multicolor sprite:");

        buttonGroupGlassMonoSprite.add(jRadioButtonGlassByteHexMonoSprite);
        jRadioButtonGlassByteHexMonoSprite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassByteHexMonoSpriteItemStateChanged(evt);
            }
        });

        buttonGroupGlassMultiSprite.add(jRadioButtonGlassByteHexMultiSprite);
        jRadioButtonGlassByteHexMultiSprite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassByteHexMultiSpriteItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxByteHexMultiSprite1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxByteHexMultiSprite1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TmpxPaneGlassByteHexMultiSprite.setEditable(false);
        TmpxPaneGlassByteHexMultiSprite.setContentType("text/html"); // NOI18N
        TmpxPaneGlassByteHexMultiSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> [byte]</b> <font color='red'>$xx..</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxByteHexMultiSprite1.setViewportView(TmpxPaneGlassByteHexMultiSprite);

        jScrollPaneTmpxByteHexMonoSprite1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxByteHexMonoSprite1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassByteHexMonoSprite.setEditable(false);
        jTextPaneGlassByteHexMonoSprite.setContentType("text/html"); // NOI18N
        jTextPaneGlassByteHexMonoSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> [byte]</b> <font color='red'>$xx..</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxByteHexMonoSprite1.setViewportView(jTextPaneGlassByteHexMonoSprite);

        buttonGroupGlassMonoSprite.add(jRadioButtonGlassByteBinMonoSprite);
        jRadioButtonGlassByteBinMonoSprite.setSelected(true);
        jRadioButtonGlassByteBinMonoSprite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassByteBinMonoSpriteItemStateChanged(evt);
            }
        });

        buttonGroupGlassMultiSprite.add(jRadioButtonGlassByteBinMultiSprite);
        jRadioButtonGlassByteBinMultiSprite.setSelected(true);
        jRadioButtonGlassByteBinMultiSprite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassByteBinMultiSpriteItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxByteBinMultiSprite1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxByteBinMultiSprite1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassByteBinMultiSprite.setEditable(false);
        jTextPaneGlassByteBinMultiSprite.setContentType("text/html"); // NOI18N
        jTextPaneGlassByteBinMultiSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[byte]</b> <font color='red'>%b..</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxByteBinMultiSprite1.setViewportView(jTextPaneGlassByteBinMultiSprite);

        jScrollPaneTmpxByteBinMonoSprite1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxByteBinMonoSprite1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassByteBinMonoSprite.setEditable(false);
        jTextPaneGlassByteBinMonoSprite.setContentType("text/html"); // NOI18N
        jTextPaneGlassByteBinMonoSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[byte]</b> <font color='red'>%b..</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxByteBinMonoSprite1.setViewportView(jTextPaneGlassByteBinMonoSprite);

        buttonGroupGlassMonoSprite.add(jRadioButtonGlassMacroHexMonoSprite);
        jRadioButtonGlassMacroHexMonoSprite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassMacroHexMonoSpriteItemStateChanged(evt);
            }
        });

        buttonGroupGlassMultiSprite.add(jRadioButtonGlassMacroHexMultiSprite);
        jRadioButtonGlassMacroHexMultiSprite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassMacroHexMultiSpriteItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxMacroHexMultiSprite1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxMacroHexMultiSprite1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassMacroHexMultiSprite.setEditable(false);
        jTextPaneGlassMacroHexMultiSprite.setContentType("text/html"); // NOI18N
        jTextPaneGlassMacroHexMultiSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac] </b> <font color='red'>$xx..</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxMacroHexMultiSprite1.setViewportView(jTextPaneGlassMacroHexMultiSprite);

        jScrollPaneTmpxMacroHexMonoSprite1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxMacroHexMonoSprite1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassMacroHexMonoSprite.setEditable(false);
        jTextPaneGlassMacroHexMonoSprite.setContentType("text/html"); // NOI18N
        jTextPaneGlassMacroHexMonoSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac] </b> <font color='red'>$xx..</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxMacroHexMonoSprite1.setViewportView(jTextPaneGlassMacroHexMonoSprite);

        buttonGroupGlassMonoSprite.add(jRadioButtonGlassMacroBinMonoSprite);
        jRadioButtonGlassMacroBinMonoSprite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassMacroBinMonoSpriteItemStateChanged(evt);
            }
        });

        buttonGroupGlassMultiSprite.add(jRadioButtonGlassMacroBinMultiSprite);
        jRadioButtonGlassMacroBinMultiSprite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassMacroBinMultiSpriteItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxMacroBinMultiSprite1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxMacroBinMultiSprite1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassMacroBinMultiSprite.setEditable(false);
        jTextPaneGlassMacroBinMultiSprite.setContentType("text/html"); // NOI18N
        jTextPaneGlassMacroBinMultiSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac] </b> <font color='red'>%b..</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxMacroBinMultiSprite1.setViewportView(jTextPaneGlassMacroBinMultiSprite);

        jScrollPaneTmpxMacroBinMonoSprite1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxMacroBinMonoSprite1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassMacroBinMonoSprite.setEditable(false);
        jTextPaneGlassMacroBinMonoSprite.setContentType("text/html"); // NOI18N
        jTextPaneGlassMacroBinMonoSprite.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac] </b> <font color='red'>%b..</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxMacroBinMonoSprite1.setViewportView(jTextPaneGlassMacroBinMonoSprite);

        jLabelGlassTribyteDeclaration.setText("Tribyte:");

        buttonGroupGlassTribyte.add(jRadioButtonGlassMacroTribyte);
        jRadioButtonGlassMacroTribyte.setSelected(true);
        jRadioButtonGlassMacroTribyte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassMacroTribyteItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxMacroTribyte1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxMacroTribyte1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassMacroTribyte.setEditable(false);
        jTextPaneGlassMacroTribyte.setContentType("text/html"); // NOI18N
        jTextPaneGlassMacroTribyte.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac]</b> <font color='red'>$xxyyzz</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxMacroTribyte1.setViewportView(jTextPaneGlassMacroTribyte);

        jLabelGlassLongDeclaration.setText("Long:");

        buttonGroupGlassLong.add(jRadioButtonGlassDdLong);
        jRadioButtonGlassDdLong.setSelected(true);
        jRadioButtonGlassDdLong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassDdLongItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxMacroLong1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxMacroLong1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassMacroLong.setEditable(false);
        jTextPaneGlassMacroLong.setContentType("text/html"); // NOI18N
        jTextPaneGlassMacroLong.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>dd</b> <font color='red'>$xxyyzzkk</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxMacroLong1.setViewportView(jTextPaneGlassMacroLong);

        jLabelGlassWordSwappedDeclaration.setText("Word Swapped:");

        buttonGroupGlassWordSwapped.add(jRadioButtonGlassMacroWordSwapped);
        jRadioButtonGlassMacroWordSwapped.setSelected(true);
        jRadioButtonGlassMacroWordSwapped.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassMacroWordSwappedItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxMacroWordSwapped1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxMacroWordSwapped1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassMacroWordSwapped.setEditable(false);
        jTextPaneGlassMacroWordSwapped.setContentType("text/html"); // NOI18N
        jTextPaneGlassMacroWordSwapped.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac]</b> <font color='red'>$yyxx</font><br>\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxMacroWordSwapped1.setViewportView(jTextPaneGlassMacroWordSwapped);

        jLabelGlassTextDeclaration.setText("Text:");

        buttonGroupGlassText.add(jRadioButtonTmpxDotText1);
        jRadioButtonTmpxDotText1.setSelected(true);
        jRadioButtonTmpxDotText1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTmpxDotText1ItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxDotText1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxDotText1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneTmpxDotText1.setEditable(false);
        jTextPaneTmpxDotText1.setContentType("text/html"); // NOI18N
        jTextPaneTmpxDotText1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> db</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxDotText1.setViewportView(jTextPaneTmpxDotText1);

        jLabelGlassNumTextDeclaration.setText("Text #num chars:");

        buttonGroupGlassNumText.add(jRadioButtonTmpxPTextNumText1);
        jRadioButtonTmpxPTextNumText1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTmpxPTextNumText1ItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxDotTextNumText1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxDotTextNumText1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneTmpxDotTextNumText1.setEditable(false);
        jTextPaneTmpxDotTextNumText1.setContentType("text/html"); // NOI18N
        jTextPaneTmpxDotTextNumText1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> .ptext</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jTextPaneTmpxDotTextNumText1.setPreferredSize(new java.awt.Dimension(66, 20));
        jScrollPaneTmpxDotTextNumText1.setViewportView(jTextPaneTmpxDotTextNumText1);

        jLabelGlassZeroTextDeclaration.setText("Text 0 terminated:");

        buttonGroupGlassZeroText.add(jRadioButtonTmpxDotNullZeroText1);
        jRadioButtonTmpxDotNullZeroText1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTmpxDotNullZeroText1ItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxDotNullZeroText1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxDotNullZeroText1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneTmpxDotNullZeroText1.setEditable(false);
        jTextPaneTmpxDotNullZeroText1.setContentType("text/html"); // NOI18N
        jTextPaneTmpxDotNullZeroText1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> .null</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxDotNullZeroText1.setViewportView(jTextPaneTmpxDotNullZeroText1);

        jLabelGlassAddressDeclaration.setText("Address:");

        buttonGroupGlassAddress.add(jRadioButtonGlassDwAddress);
        jRadioButtonGlassDwAddress.setSelected(true);
        jRadioButtonGlassDwAddress.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassDwAddressItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxDotAddrAddress1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxDotAddrAddress1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassDwAddress.setEditable(false);
        jTextPaneGlassDwAddress.setContentType("text/html"); // NOI18N
        jTextPaneGlassDwAddress.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> dw</b> <font color='red'>$xxyy</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxDotAddrAddress1.setViewportView(jTextPaneGlassDwAddress);

        jLabelTmpxGlassStackWordDeclaration.setText("Stack Word:");

        buttonGroupGlassWord.add(jRadioButtonGlassMacroStackWord);
        jRadioButtonGlassMacroStackWord.setSelected(true);
        jRadioButtonGlassMacroStackWord.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassMacroStackWordItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxDotRtaStackWord1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxDotRtaStackWord1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassMacroStackWord.setEditable(false);
        jTextPaneGlassMacroStackWord.setContentType("text/html"); // NOI18N
        jTextPaneGlassMacroStackWord.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>[.mac]</b> <font color='red'>$xxyy</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxDotRtaStackWord1.setViewportView(jTextPaneGlassMacroStackWord);

        jLabelGlassHighTextDeclaration.setText("Text '1' terminated:");

        buttonGroupGlassHighText.add(jRadioButtonTmpxDotShiftHighText1);
        jRadioButtonTmpxDotShiftHighText1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTmpxDotShiftHighText1ItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxDotShiftHighText1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxDotShiftHighText1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneTmpxDotShiftHighText1.setEditable(false);
        jTextPaneTmpxDotShiftHighText1.setContentType("text/html"); // NOI18N
        jTextPaneTmpxDotShiftHighText1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> .shift</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jTextPaneTmpxDotShiftHighText1.setPreferredSize(new java.awt.Dimension(66, 20));
        jScrollPaneTmpxDotShiftHighText1.setViewportView(jTextPaneTmpxDotShiftHighText1);

        jLabelGlassShiftTextDeclaration.setText("Text left shifted:");

        buttonGroupGlassShiftText.add(jRadioButtonTmpxDotShiflShiftText1);
        jRadioButtonTmpxDotShiflShiftText1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTmpxDotShiflShiftText1ItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxDotShiftlShiftText1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxDotShiftlShiftText1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneTmpxDotShiflShiftText1.setEditable(false);
        jTextPaneTmpxDotShiflShiftText1.setContentType("text/html"); // NOI18N
        jTextPaneTmpxDotShiflShiftText1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> .shiftl</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jTextPaneTmpxDotShiflShiftText1.setPreferredSize(new java.awt.Dimension(66, 20));
        jScrollPaneTmpxDotShiftlShiftText1.setViewportView(jTextPaneTmpxDotShiflShiftText1);

        jLabelGlassScreenTextDeclaration.setText("Text to screen code:");

        buttonGroupGlassScreenText.add(jRadioButtonTmpxDotScreenText1);
        jRadioButtonTmpxDotScreenText1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTmpxDotScreenText1ItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxDotScreenText1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxDotScreenText1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneTmpxDotScreenText1.setEditable(false);
        jTextPaneTmpxDotScreenText1.setContentType("text/html"); // NOI18N
        jTextPaneTmpxDotScreenText1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> .screen</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxDotScreenText1.setViewportView(jTextPaneTmpxDotScreenText1);

        jLabelGlassPetasciiTextDeclaration.setText("Text to petascii code:");

        buttonGroupGlassPetsciiText.add(jRadioButtonTmpxDotPetasciiText1);
        jRadioButtonTmpxDotPetasciiText1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTmpxDotPetasciiText1ItemStateChanged(evt);
            }
        });

        jScrollPaneTmpxDotPetasciiText1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTmpxDotPetasciiText1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneTmpxDotPetasciiText1.setEditable(false);
        jTextPaneTmpxDotPetasciiText1.setContentType("text/html"); // NOI18N
        jTextPaneTmpxDotPetasciiText1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b> .text</b> <font color='red'>\"xxx\"</font><br>\n\n    </p>\n  </body>\n</html>\n");
        jScrollPaneTmpxDotPetasciiText1.setViewportView(jTextPaneTmpxDotPetasciiText1);

        buttonGroupGlassLabel.add(jRadioButtonGlassLabelNameColon);
        jRadioButtonGlassLabelNameColon.setSelected(true);
        jRadioButtonGlassLabelNameColon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonGlassLabelNameColonItemStateChanged(evt);
            }
        });

        jScrollPaneDasmLabelNameColon.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneDasmLabelNameColon.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPaneGlassLabelNameColon.setEditable(false);
        jTextPaneGlassLabelNameColon.setContentType("text/html"); // NOI18N
        jTextPaneGlassLabelNameColon.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n     <font color='black'>zzzz</font><b>:</b>\n    </p>\n  </body>\n</html>\n");
        jScrollPaneDasmLabelNameColon.setViewportView(jTextPaneGlassLabelNameColon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGlassStartingDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGlassOriginDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGlassCommentDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTmpxBlockCommentDeclaration1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGlassHighTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGlassShiftTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGlassScreenTextDeclaration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGlassLabelDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassByteDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassWordDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassWordSwappedDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassTribyteDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassLongDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassAddressDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTmpxGlassStackWordDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassMonoSpriteDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassMultiSpriteDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassTextDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassNumTextDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassZeroTextDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGlassPetasciiTextDeclaration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonGlassFakeStarting)
                    .addComponent(jRadioButtonGlassOrigin)
                    .addComponent(jRadioButtonGlassSemicolonComment)
                    .addComponent(jRadioButtonTmpxSemicolonBlockComment1)
                    .addComponent(jRadioButtonGlassLabelName)
                    .addComponent(jRadioButtonGlassDbByte)
                    .addComponent(jRadioButtonGlassDwWord)
                    .addComponent(jRadioButtonGlassMacroWordSwapped)
                    .addComponent(jRadioButtonGlassMacroTribyte)
                    .addComponent(jRadioButtonGlassDdLong)
                    .addComponent(jRadioButtonGlassDwAddress)
                    .addComponent(jRadioButtonGlassMacroStackWord)
                    .addComponent(jRadioButtonGlassByteHexMonoSprite)
                    .addComponent(jRadioButtonGlassByteHexMultiSprite)
                    .addComponent(jRadioButtonTmpxDotText1)
                    .addComponent(jRadioButtonTmpxPTextNumText1)
                    .addComponent(jRadioButtonTmpxDotNullZeroText1)
                    .addComponent(jRadioButtonTmpxDotShiftHighText1)
                    .addComponent(jRadioButtonTmpxDotShiflShiftText1)
                    .addComponent(jRadioButtonTmpxDotScreenText1)
                    .addComponent(jRadioButtonTmpxDotPetasciiText1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneGlassFakeStarting)
                    .addComponent(jScrollPaneTmpxAsterixOrigin1)
                    .addComponent(jScrollPaneTmpxSemicolonComment1)
                    .addComponent(jScrollPaneTmpxSemicolonBlockComment1)
                    .addComponent(jScrollPaneGlassByte)
                    .addComponent(jScrollPaneGlassWord)
                    .addComponent(jScrollPaneGlassDotWord)
                    .addComponent(jScrollPaneTmpxMacroWordSwapped1)
                    .addComponent(jScrollPaneTmpxMacroTribyte1)
                    .addComponent(jScrollPaneTmpxMacroLong1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPaneTmpxDotAddrAddress1)
                    .addComponent(jScrollPaneTmpxDotRtaStackWord1)
                    .addComponent(jScrollPaneTmpxByteHexMonoSprite1)
                    .addComponent(jScrollPaneTmpxByteHexMultiSprite1)
                    .addComponent(jScrollPaneTmpxDotText1)
                    .addComponent(jScrollPaneTmpxDotTextNumText1)
                    .addComponent(jScrollPaneTmpxDotNullZeroText1)
                    .addComponent(jScrollPaneTmpxDotShiftHighText1)
                    .addComponent(jScrollPaneTmpxDotShiftlShiftText1)
                    .addComponent(jScrollPaneTmpxDotScreenText1)
                    .addComponent(jScrollPaneTmpxDotPetasciiText1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonGlassByteBinMonoSprite)
                            .addComponent(jRadioButtonGlassByteBinMultiSprite))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPaneTmpxByteBinMonoSprite1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jScrollPaneTmpxByteBinMultiSprite1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonGlassLabelNameColon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneDasmLabelNameColon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonGlassMacroHexMonoSprite)
                    .addComponent(jRadioButtonGlassMacroHexMultiSprite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTmpxMacroHexMonoSprite1)
                    .addComponent(jScrollPaneTmpxMacroHexMultiSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonGlassMacroBinMultiSprite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneTmpxMacroBinMultiSprite1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonGlassMacroBinMonoSprite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneTmpxMacroBinMonoSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassStartingDeclaration)
                    .addComponent(jRadioButtonGlassFakeStarting)
                    .addComponent(jScrollPaneGlassFakeStarting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassOriginDeclaration)
                    .addComponent(jRadioButtonGlassOrigin)
                    .addComponent(jScrollPaneTmpxAsterixOrigin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassCommentDeclaration)
                    .addComponent(jRadioButtonGlassSemicolonComment)
                    .addComponent(jScrollPaneTmpxSemicolonComment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelTmpxBlockCommentDeclaration1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTmpxSemicolonBlockComment1)
                    .addComponent(jScrollPaneTmpxSemicolonBlockComment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassLabelDeclaration)
                    .addComponent(jRadioButtonGlassLabelName)
                    .addComponent(jScrollPaneGlassByte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassLabelNameColon)
                    .addComponent(jScrollPaneDasmLabelNameColon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassByteDeclaration)
                    .addComponent(jRadioButtonGlassDbByte)
                    .addComponent(jScrollPaneGlassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassWordDeclaration)
                    .addComponent(jRadioButtonGlassDwWord)
                    .addComponent(jScrollPaneGlassDotWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassWordSwappedDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassMacroWordSwapped)
                    .addComponent(jScrollPaneTmpxMacroWordSwapped1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassTribyteDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassMacroTribyte)
                    .addComponent(jScrollPaneTmpxMacroTribyte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassLongDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassDdLong)
                    .addComponent(jScrollPaneTmpxMacroLong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassAddressDeclaration)
                    .addComponent(jRadioButtonGlassDwAddress)
                    .addComponent(jScrollPaneTmpxDotAddrAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelTmpxGlassStackWordDeclaration)
                    .addComponent(jRadioButtonGlassMacroStackWord)
                    .addComponent(jScrollPaneTmpxDotRtaStackWord1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassMonoSpriteDeclaration)
                    .addComponent(jRadioButtonGlassByteHexMonoSprite)
                    .addComponent(jScrollPaneTmpxByteHexMonoSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassByteBinMonoSprite)
                    .addComponent(jScrollPaneTmpxByteBinMonoSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassMacroHexMonoSprite)
                    .addComponent(jScrollPaneTmpxMacroHexMonoSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassMacroBinMonoSprite)
                    .addComponent(jScrollPaneTmpxMacroBinMonoSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassMultiSpriteDeclaration)
                    .addComponent(jRadioButtonGlassByteHexMultiSprite)
                    .addComponent(jScrollPaneTmpxByteHexMultiSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassByteBinMultiSprite)
                    .addComponent(jScrollPaneTmpxByteBinMultiSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassMacroHexMultiSprite)
                    .addComponent(jScrollPaneTmpxMacroHexMultiSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonGlassMacroBinMultiSprite)
                    .addComponent(jScrollPaneTmpxMacroBinMultiSprite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassTextDeclaration)
                    .addComponent(jRadioButtonTmpxDotText1)
                    .addComponent(jScrollPaneTmpxDotText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassNumTextDeclaration)
                    .addComponent(jRadioButtonTmpxPTextNumText1)
                    .addComponent(jScrollPaneTmpxDotTextNumText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassZeroTextDeclaration)
                    .addComponent(jRadioButtonTmpxDotNullZeroText1)
                    .addComponent(jScrollPaneTmpxDotNullZeroText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassHighTextDeclaration)
                    .addComponent(jRadioButtonTmpxDotShiftHighText1)
                    .addComponent(jScrollPaneTmpxDotShiftHighText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassShiftTextDeclaration)
                    .addComponent(jRadioButtonTmpxDotShiflShiftText1)
                    .addComponent(jScrollPaneTmpxDotShiftlShiftText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassScreenTextDeclaration)
                    .addComponent(jRadioButtonTmpxDotScreenText1)
                    .addComponent(jScrollPaneTmpxDotScreenText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGlassPetasciiTextDeclaration)
                    .addComponent(jRadioButtonTmpxDotPetasciiText1)
                    .addComponent(jScrollPaneTmpxDotPetasciiText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonGlassDwWordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassDwWordItemStateChanged
      option.glassWord=Assembler.Word.DW_WORD;       
    }//GEN-LAST:event_jRadioButtonGlassDwWordItemStateChanged

    private void jRadioButtonGlassSemicolonCommentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassSemicolonCommentItemStateChanged
      option.glassComment=Assembler.Comment.SEMICOLON;     
    }//GEN-LAST:event_jRadioButtonGlassSemicolonCommentItemStateChanged

    private void jRadioButtonTmpxSemicolonBlockComment1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTmpxSemicolonBlockComment1ItemStateChanged
      option.glassBlockComment=Assembler.BlockComment.SEMICOLON; 
    }//GEN-LAST:event_jRadioButtonTmpxSemicolonBlockComment1ItemStateChanged

    private void jRadioButtonGlassOriginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassOriginItemStateChanged
       option.glassOrigin=Assembler.Origin.ORG;
    }//GEN-LAST:event_jRadioButtonGlassOriginItemStateChanged

    private void jRadioButtonGlassFakeStartingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassFakeStartingItemStateChanged
        option.glassStarting=Assembler.Starting.FAKEZ;
    }//GEN-LAST:event_jRadioButtonGlassFakeStartingItemStateChanged

    private void jRadioButtonGlassByteHexMonoSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassByteHexMonoSpriteItemStateChanged
        option.glassMonoSprite=Assembler.MonoSprite.BYTE_HEX;
    }//GEN-LAST:event_jRadioButtonGlassByteHexMonoSpriteItemStateChanged

    private void jRadioButtonGlassByteHexMultiSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassByteHexMultiSpriteItemStateChanged
       option.glassMultiSprite=Assembler.MultiSprite.BYTE_HEX;
    }//GEN-LAST:event_jRadioButtonGlassByteHexMultiSpriteItemStateChanged

    private void jRadioButtonGlassByteBinMonoSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassByteBinMonoSpriteItemStateChanged
       option.glassMonoSprite=Assembler.MonoSprite.BYTE_BIN;
    }//GEN-LAST:event_jRadioButtonGlassByteBinMonoSpriteItemStateChanged

    private void jRadioButtonGlassByteBinMultiSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassByteBinMultiSpriteItemStateChanged
       option.glassMultiSprite=Assembler.MultiSprite.BYTE_BIN;
    }//GEN-LAST:event_jRadioButtonGlassByteBinMultiSpriteItemStateChanged

    private void jRadioButtonGlassMacroHexMonoSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassMacroHexMonoSpriteItemStateChanged
       option.glassMonoSprite=Assembler.MonoSprite.MACRO5_HEX;
    }//GEN-LAST:event_jRadioButtonGlassMacroHexMonoSpriteItemStateChanged

    private void jRadioButtonGlassMacroHexMultiSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassMacroHexMultiSpriteItemStateChanged
       option.glassMultiSprite=Assembler.MultiSprite.MACRO5_HEX;
    }//GEN-LAST:event_jRadioButtonGlassMacroHexMultiSpriteItemStateChanged

    private void jRadioButtonGlassMacroBinMonoSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassMacroBinMonoSpriteItemStateChanged
       option.glassMonoSprite=Assembler.MonoSprite.MACRO5_BIN;
    }//GEN-LAST:event_jRadioButtonGlassMacroBinMonoSpriteItemStateChanged

    private void jRadioButtonGlassMacroBinMultiSpriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassMacroBinMultiSpriteItemStateChanged
      option.glassMultiSprite=Assembler.MultiSprite.MACRO5_BIN;
    }//GEN-LAST:event_jRadioButtonGlassMacroBinMultiSpriteItemStateChanged

    private void jRadioButtonGlassMacroTribyteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassMacroTribyteItemStateChanged
       option.glassTribyte=Assembler.Tribyte.MACRO5_TRIBYTE;
    }//GEN-LAST:event_jRadioButtonGlassMacroTribyteItemStateChanged

    private void jRadioButtonGlassDdLongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassDdLongItemStateChanged
       option.glassLong=Assembler.Long.DD_LONG;
    }//GEN-LAST:event_jRadioButtonGlassDdLongItemStateChanged

    private void jRadioButtonGlassMacroWordSwappedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassMacroWordSwappedItemStateChanged
       option.glassWordSwapped=Assembler.WordSwapped.MACRO5_WORD_SWAPPED;
    }//GEN-LAST:event_jRadioButtonGlassMacroWordSwappedItemStateChanged

    private void jRadioButtonTmpxDotText1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTmpxDotText1ItemStateChanged
       option.glassText=Assembler.Text.DB_BYTE_TEXT;
    }//GEN-LAST:event_jRadioButtonTmpxDotText1ItemStateChanged

    private void jRadioButtonTmpxPTextNumText1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTmpxPTextNumText1ItemStateChanged
        
    }//GEN-LAST:event_jRadioButtonTmpxPTextNumText1ItemStateChanged

    private void jRadioButtonTmpxDotNullZeroText1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTmpxDotNullZeroText1ItemStateChanged
        
    }//GEN-LAST:event_jRadioButtonTmpxDotNullZeroText1ItemStateChanged

    private void jRadioButtonGlassDwAddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassDwAddressItemStateChanged
      option.glassAddress=Assembler.Address.DW_ADDR;
    }//GEN-LAST:event_jRadioButtonGlassDwAddressItemStateChanged

    private void jRadioButtonGlassMacroStackWordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassMacroStackWordItemStateChanged
      option.glassStackWord=Assembler.StackWord.MACRO4_STACKWORD;
    }//GEN-LAST:event_jRadioButtonGlassMacroStackWordItemStateChanged

    private void jRadioButtonTmpxDotShiftHighText1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTmpxDotShiftHighText1ItemStateChanged
       
    }//GEN-LAST:event_jRadioButtonTmpxDotShiftHighText1ItemStateChanged

    private void jRadioButtonTmpxDotShiflShiftText1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTmpxDotShiflShiftText1ItemStateChanged
        
    }//GEN-LAST:event_jRadioButtonTmpxDotShiflShiftText1ItemStateChanged

    private void jRadioButtonTmpxDotScreenText1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTmpxDotScreenText1ItemStateChanged
        
    }//GEN-LAST:event_jRadioButtonTmpxDotScreenText1ItemStateChanged

    private void jRadioButtonTmpxDotPetasciiText1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTmpxDotPetasciiText1ItemStateChanged
       
    }//GEN-LAST:event_jRadioButtonTmpxDotPetasciiText1ItemStateChanged

    private void jRadioButtonGlassLabelNameColonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassLabelNameColonItemStateChanged
        option.glassLabel=Assembler.Label.NAME_COLON;
    }//GEN-LAST:event_jRadioButtonGlassLabelNameColonItemStateChanged

    private void jRadioButtonGlassLabelNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassLabelNameItemStateChanged
        option.glassLabel=Assembler.Label.NAME;
    }//GEN-LAST:event_jRadioButtonGlassLabelNameItemStateChanged

    private void jRadioButtonGlassDbByteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonGlassDbByteItemStateChanged
        option.glassByte=Assembler.Byte.DB_BYTE;
    }//GEN-LAST:event_jRadioButtonGlassDbByteItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TmpxPaneGlassByteHexMultiSprite;
    private javax.swing.ButtonGroup buttonGroupGlassAddress;
    private javax.swing.ButtonGroup buttonGroupGlassBlockComment;
    private javax.swing.ButtonGroup buttonGroupGlassByte;
    private javax.swing.ButtonGroup buttonGroupGlassComment;
    private javax.swing.ButtonGroup buttonGroupGlassHighText;
    private javax.swing.ButtonGroup buttonGroupGlassLabel;
    private javax.swing.ButtonGroup buttonGroupGlassLong;
    private javax.swing.ButtonGroup buttonGroupGlassMonoSprite;
    private javax.swing.ButtonGroup buttonGroupGlassMultiSprite;
    private javax.swing.ButtonGroup buttonGroupGlassNumText;
    private javax.swing.ButtonGroup buttonGroupGlassOrigin;
    private javax.swing.ButtonGroup buttonGroupGlassPetsciiText;
    private javax.swing.ButtonGroup buttonGroupGlassScreenText;
    private javax.swing.ButtonGroup buttonGroupGlassShiftText;
    private javax.swing.ButtonGroup buttonGroupGlassStackWord;
    private javax.swing.ButtonGroup buttonGroupGlassStarting;
    private javax.swing.ButtonGroup buttonGroupGlassText;
    private javax.swing.ButtonGroup buttonGroupGlassTribyte;
    private javax.swing.ButtonGroup buttonGroupGlassWord;
    private javax.swing.ButtonGroup buttonGroupGlassWordSwapped;
    private javax.swing.ButtonGroup buttonGroupGlassZeroText;
    private javax.swing.JLabel jLabelGlassAddressDeclaration;
    private javax.swing.JLabel jLabelGlassByteDeclaration;
    private javax.swing.JLabel jLabelGlassCommentDeclaration;
    private javax.swing.JLabel jLabelGlassHighTextDeclaration;
    private javax.swing.JLabel jLabelGlassLabelDeclaration;
    private javax.swing.JLabel jLabelGlassLongDeclaration;
    private javax.swing.JLabel jLabelGlassMonoSpriteDeclaration;
    private javax.swing.JLabel jLabelGlassMultiSpriteDeclaration;
    private javax.swing.JLabel jLabelGlassNumTextDeclaration;
    private javax.swing.JLabel jLabelGlassOriginDeclaration;
    private javax.swing.JLabel jLabelGlassPetasciiTextDeclaration;
    private javax.swing.JLabel jLabelGlassScreenTextDeclaration;
    private javax.swing.JLabel jLabelGlassShiftTextDeclaration;
    private javax.swing.JLabel jLabelGlassStartingDeclaration;
    private javax.swing.JLabel jLabelGlassTextDeclaration;
    private javax.swing.JLabel jLabelGlassTribyteDeclaration;
    private javax.swing.JLabel jLabelGlassWordDeclaration;
    private javax.swing.JLabel jLabelGlassWordSwappedDeclaration;
    private javax.swing.JLabel jLabelGlassZeroTextDeclaration;
    private javax.swing.JLabel jLabelTmpxBlockCommentDeclaration1;
    private javax.swing.JLabel jLabelTmpxGlassStackWordDeclaration;
    private javax.swing.JRadioButton jRadioButtonGlassByteBinMonoSprite;
    private javax.swing.JRadioButton jRadioButtonGlassByteBinMultiSprite;
    private javax.swing.JRadioButton jRadioButtonGlassByteHexMonoSprite;
    private javax.swing.JRadioButton jRadioButtonGlassByteHexMultiSprite;
    private javax.swing.JRadioButton jRadioButtonGlassDbByte;
    private javax.swing.JRadioButton jRadioButtonGlassDdLong;
    private javax.swing.JRadioButton jRadioButtonGlassDwAddress;
    private javax.swing.JRadioButton jRadioButtonGlassDwWord;
    private javax.swing.JRadioButton jRadioButtonGlassFakeStarting;
    private javax.swing.JRadioButton jRadioButtonGlassLabelName;
    private javax.swing.JRadioButton jRadioButtonGlassLabelNameColon;
    private javax.swing.JRadioButton jRadioButtonGlassMacroBinMonoSprite;
    private javax.swing.JRadioButton jRadioButtonGlassMacroBinMultiSprite;
    private javax.swing.JRadioButton jRadioButtonGlassMacroHexMonoSprite;
    private javax.swing.JRadioButton jRadioButtonGlassMacroHexMultiSprite;
    private javax.swing.JRadioButton jRadioButtonGlassMacroStackWord;
    private javax.swing.JRadioButton jRadioButtonGlassMacroTribyte;
    private javax.swing.JRadioButton jRadioButtonGlassMacroWordSwapped;
    private javax.swing.JRadioButton jRadioButtonGlassOrigin;
    private javax.swing.JRadioButton jRadioButtonGlassSemicolonComment;
    private javax.swing.JRadioButton jRadioButtonTmpxDotNullZeroText1;
    private javax.swing.JRadioButton jRadioButtonTmpxDotPetasciiText1;
    private javax.swing.JRadioButton jRadioButtonTmpxDotScreenText1;
    private javax.swing.JRadioButton jRadioButtonTmpxDotShiflShiftText1;
    private javax.swing.JRadioButton jRadioButtonTmpxDotShiftHighText1;
    private javax.swing.JRadioButton jRadioButtonTmpxDotText1;
    private javax.swing.JRadioButton jRadioButtonTmpxPTextNumText1;
    private javax.swing.JRadioButton jRadioButtonTmpxSemicolonBlockComment1;
    private javax.swing.JScrollPane jScrollPaneDasmLabelNameColon;
    private javax.swing.JScrollPane jScrollPaneGlassByte;
    private javax.swing.JScrollPane jScrollPaneGlassDotWord;
    private javax.swing.JScrollPane jScrollPaneGlassFakeStarting;
    private javax.swing.JScrollPane jScrollPaneGlassWord;
    private javax.swing.JScrollPane jScrollPaneTmpxAsterixOrigin1;
    private javax.swing.JScrollPane jScrollPaneTmpxByteBinMonoSprite1;
    private javax.swing.JScrollPane jScrollPaneTmpxByteBinMultiSprite1;
    private javax.swing.JScrollPane jScrollPaneTmpxByteHexMonoSprite1;
    private javax.swing.JScrollPane jScrollPaneTmpxByteHexMultiSprite1;
    private javax.swing.JScrollPane jScrollPaneTmpxDotAddrAddress1;
    private javax.swing.JScrollPane jScrollPaneTmpxDotNullZeroText1;
    private javax.swing.JScrollPane jScrollPaneTmpxDotPetasciiText1;
    private javax.swing.JScrollPane jScrollPaneTmpxDotRtaStackWord1;
    private javax.swing.JScrollPane jScrollPaneTmpxDotScreenText1;
    private javax.swing.JScrollPane jScrollPaneTmpxDotShiftHighText1;
    private javax.swing.JScrollPane jScrollPaneTmpxDotShiftlShiftText1;
    private javax.swing.JScrollPane jScrollPaneTmpxDotText1;
    private javax.swing.JScrollPane jScrollPaneTmpxDotTextNumText1;
    private javax.swing.JScrollPane jScrollPaneTmpxMacroBinMonoSprite1;
    private javax.swing.JScrollPane jScrollPaneTmpxMacroBinMultiSprite1;
    private javax.swing.JScrollPane jScrollPaneTmpxMacroHexMonoSprite1;
    private javax.swing.JScrollPane jScrollPaneTmpxMacroHexMultiSprite1;
    private javax.swing.JScrollPane jScrollPaneTmpxMacroLong1;
    private javax.swing.JScrollPane jScrollPaneTmpxMacroTribyte1;
    private javax.swing.JScrollPane jScrollPaneTmpxMacroWordSwapped1;
    private javax.swing.JScrollPane jScrollPaneTmpxSemicolonBlockComment1;
    private javax.swing.JScrollPane jScrollPaneTmpxSemicolonComment1;
    private javax.swing.JTextPane jTextPaneGlassByteBinMonoSprite;
    private javax.swing.JTextPane jTextPaneGlassByteBinMultiSprite;
    private javax.swing.JTextPane jTextPaneGlassByteHexMonoSprite;
    private javax.swing.JTextPane jTextPaneGlassDbByte;
    private javax.swing.JTextPane jTextPaneGlassDwAddress;
    private javax.swing.JTextPane jTextPaneGlassDwWord;
    private javax.swing.JTextPane jTextPaneGlassFakeStarting;
    private javax.swing.JTextPane jTextPaneGlassLabelName;
    private javax.swing.JTextPane jTextPaneGlassLabelNameColon;
    private javax.swing.JTextPane jTextPaneGlassMacroBinMonoSprite;
    private javax.swing.JTextPane jTextPaneGlassMacroBinMultiSprite;
    private javax.swing.JTextPane jTextPaneGlassMacroHexMonoSprite;
    private javax.swing.JTextPane jTextPaneGlassMacroHexMultiSprite;
    private javax.swing.JTextPane jTextPaneGlassMacroLong;
    private javax.swing.JTextPane jTextPaneGlassMacroStackWord;
    private javax.swing.JTextPane jTextPaneGlassMacroTribyte;
    private javax.swing.JTextPane jTextPaneGlassMacroWordSwapped;
    private javax.swing.JTextPane jTextPaneGlassOrigin;
    private javax.swing.JTextPane jTextPaneGlassSemicolonComment;
    private javax.swing.JTextPane jTextPaneTmpxDotNullZeroText1;
    private javax.swing.JTextPane jTextPaneTmpxDotPetasciiText1;
    private javax.swing.JTextPane jTextPaneTmpxDotScreenText1;
    private javax.swing.JTextPane jTextPaneTmpxDotShiflShiftText1;
    private javax.swing.JTextPane jTextPaneTmpxDotShiftHighText1;
    private javax.swing.JTextPane jTextPaneTmpxDotText1;
    private javax.swing.JTextPane jTextPaneTmpxDotTextNumText1;
    private javax.swing.JTextPane jTextPaneTmpxSemicolonBlockComment1;
    // End of variables declaration//GEN-END:variables
 
  /**
   * Apply the option for TMPx
   */
  public void applyOptionGlass() {
    switch (option.glassStarting) {
      case FAKEZ:
        jRadioButtonGlassFakeStarting.setSelected(true);   
        break;
    }
    
    switch (option.glassOrigin) {
      case DOT_ORG:
      case ORG:
        jRadioButtonGlassOrigin.setSelected(true);  
        break;
    }      
    
    switch (option.glassLabel) {
      case NAME:
        jRadioButtonGlassLabelName.setSelected(true);
        break;
      case NAME_COLON:
        jRadioButtonGlassLabelNameColon.setSelected(true);  
        break;  
    }
    
    switch (option.glassComment) {
      case SEMICOLON:
        jRadioButtonGlassSemicolonComment.setSelected(true);
        break;               
    }    
    
    switch (option.glassByte) {
      case DB_BYTE:  
        jRadioButtonGlassDbByte.setSelected(true);
        break;      
    }
    
    switch (option.glassWord) {
      case DOT_WORD:  
        jRadioButtonGlassDwWord.setSelected(true);
        break;          
    } 
    
    switch (option.glassWordSwapped) {
      case MACRO5_WORD_SWAPPED:  
        jRadioButtonGlassMacroWordSwapped.setSelected(true);
        break;          
    }
    
    switch (option.glassTribyte) {
      case MACRO5_TRIBYTE:  
        jRadioButtonGlassMacroTribyte.setSelected(true);
        break;          
    }
    
    switch (option.glassLong) {
      case DD_LONG:  
        jRadioButtonGlassDdLong.setSelected(true);
        break;          
    }
    
    switch (option.glassAddress) {
      case DW_ADDR:  
        jRadioButtonGlassDwAddress.setSelected(true);
        break;          
    }
    
    switch (option.glassStackWord) {
      case MACRO4_STACKWORD:  
        jRadioButtonGlassMacroStackWord.setSelected(true);
        break;          
    }
    
    switch (option.dasmMonoSprite) {
      case BYTE_HEX:
        jRadioButtonGlassByteHexMonoSprite.setSelected(true);
        break;
      case BYTE_BIN:
        jRadioButtonGlassByteBinMonoSprite.setSelected(true);
        break;
      case MACRO5_HEX:
        jRadioButtonGlassMacroHexMonoSprite.setSelected(true);
        break;  
      case MACRO5_BIN:
        jRadioButtonGlassMacroBinMonoSprite.setSelected(true);
        break;  
    }
    
    switch (option.dasmMultiSprite) {
      case BYTE_HEX:
        jRadioButtonGlassByteHexMultiSprite.setSelected(true);
        break;
      case BYTE_BIN:
        jRadioButtonGlassByteBinMultiSprite.setSelected(true);
        break;
      case MACRO5_HEX:
        jRadioButtonGlassMacroHexMultiSprite.setSelected(true);
        break;  
      case MACRO5_BIN:
        jRadioButtonGlassMacroBinMultiSprite.setSelected(true);
        break;  
    }    
  }
}

