/**
 * @(#)JPercPanel.java 2019/12/29
 *
 * ICE Team free software group
 *
 * This file is part of JIIT64 Java Ice Team Tracker 64
 * See README for copyright notice.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 *  02111-1307  USA.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package sw_emulator.swing;

import java.awt.Color;

/**
 * Panel for % of completion
 * 
 * @author ice
 */
public class JPanelPerc extends javax.swing.JPanel {   
    Color start=Color.GREEN;
    Color end=Color.RED;

    /**
     * Creates new form JPanelPerc
     */
    public JPanelPerc() {
        initComponents();
        
        setPerc(-1);
    }
    
    /**
     * Set the actual perc
     * 
     * @param perc the perc %
     */
    public void setPerc(float perc) {        
      if (perc<0) {
        jLabelPerc.setText("%");  
        this.setBackground(Color.WHITE);
        return;
      }
      
      if (perc>1) perc=1;
      
      float blending=perc;
      float inverse_blending = 1-blending;

      float red = start.getRed()*blending + end.getRed()*inverse_blending;
      float green = start.getGreen()*blending + end.getGreen()*inverse_blending;
      float blue = start.getBlue()*blending + end.getBlue()*inverse_blending;
   
      Color blended = new Color (red / 255, green / 255, blue / 255);
      this.setBackground(blended);
      jLabelPerc.setText((int)(perc*100)+"%");
      this.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPerc = new javax.swing.JLabel();

        setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(54, 36));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(54, 36));
        setRequestFocusEnabled(false);
        setLayout(null);

        jLabelPerc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPerc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerc.setText("0%");
        jLabelPerc.setToolTipText("Percentage of reverse engineering");
        add(jLabelPerc);
        jLabelPerc.setBounds(7, 5, 70, 26);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPerc;
    // End of variables declaration//GEN-END:variables
}
